### ISSUE TITLE
Outline view does not show ApexClass contents if first minimized

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#102]
The Outline view will not show the ApexClass methods, attributes, etc. if the Outline view is minimized.  

Steps to reproduce:
- Install Force.com IDE v33.0.0.201503191609
- Minimize the Outline view
- Open an ApexClass
- Show the Outline view
  - Failure point: view does not show class contents

Workaround: Show the Outline view before you open the ApexClass

Hope this helps.

**Comment by AndyRouse42** [comment]
Thank you for this workaround - I'm experiencing the same issue.

**Comment by franmico** [comment]
Omg! Thank you so much - it was driving me crazy!
