### ISSUE TITLE
Increase Apex Test Runner log panel size

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#107]
It would appear that the log panel used in the Apex Test Runner view only shows about 1MB worth of data.  Can we get that increased to 2MB?

The standard UI Developer Console currently shows about 2 MB log files before it truncates the log size.  Having this Apex Test Runner view log viewer only show 1 MB is inconsistent and deters from its usage.

**Comment by vazexqi** [comment]
@ImJohnMDaniel This should be fixed in the latest beta. We have switched over to using the Tooling API to run tests and use TraceFlags to control the log output.

CC: @DatGuyJonathan

**Comment by ImJohnMDaniel** [comment]
@vazexqi, Sounds good.  Thanks for the update.

Also, am I correct that the latest beta only works for Summer15 orgs?

**Comment by vazexqi** [comment]
@ImJohnMDaniel: Yes. It's using v34 of the API, so Summer '15 orgs only (sandbox should have been updated already as of last week).

**Comment by ImJohnMDaniel** [comment]
Thanks.  Unfortunately, I am only working in DE orgs at the moment. ;-)  That's ok.  Definitely excited about what I have read is coming.  Can't wait!!  Thanks for the effort!
