### ISSUE TITLE
Errors listed in Problems window do not clear out

### ISSUE THREAD

**Issue by pranavraulkar** [forcedotcom/idecore#112]
Even after fixing the issues reported for a apex class, the error list in the 'Problems' window do not clear out. Even after an project refresh from server, the list stays as it is and the error markers show in the respective files too.

OS: Windows 8.1
Eclipse Version: 4.4.2
Force.com IDE Version: 33.0.0.201504091124

**Comment by vazexqi** [comment]
Acknowledged. I can reproduce this on my end.

For now, you can open the "Problems" View, right-click on "Errors" and then "Delete" to clear them off manually. This is not a permanent solution but at least it will let you know which errors are current and which are obsolete.

**Comment by cropredy** [comment]
Another workaround is to turn off Tooling API in Project Properties although one could argue this defeats the purpose of using the latest IDE

**Comment by aleramesh** [comment]
@vazexqi 

At times when I try to delete the errors in Problems view manually, the delete option is deleted. Do you know why? I cannot figure out why this happens random.

Here is the screenshot showing delete option is disabled, When I try to delete manually:

<img width="603" alt="eclipse_error_delete" src="https://cloud.githubusercontent.com/assets/11079913/9374191/5120af2c-46c1-11e5-9c20-0029fd1bff38.png">

**Comment by vazexqi** [comment]
@aleramesh - What happens if you just select the errors (vs selecting the warnings as you have done)?

**Comment by aleramesh** [comment]
Thanks for the reply. When I just select Errors, I was able to delete successfully. Thanks for that tip!

**Comment by afawcett** [comment]
@vazexqi any update on this issue? This problem makes it really hard to work on code that your refactor or sweeping, i'm having to manually clear errors before each save. This makes for a very slow developer workflow. Thanks, enjoying getting used my old friend Force.com IDE again! 👍
