### ISSUE TITLE
Feature Request: Syntax highlighting for javascript code

### ISSUE THREAD

**Issue by Lanceshi2** [forcedotcom/idecore#114]
Not sure whether this has already been worked on. But it seems to me that syntax highlighting for javascript code will be highly beneficial to lots of users. By using adding a javascript editor and default .page files to that will resolve the issue but will lose the support for Visualforce tags. If this hasn't been worked on, I am more than happy to volunteer to do that.

**Comment by RJPalombo** [comment]
+1
