### ISSUE TITLE
Add/Remove Metadata Components disabled on lower project directories

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#116]
@vazexqi - G'Day!

Working with the v34 beta and I noticed that the "Add/Remove Metadata Components" context menu option is disabled in all of the lower project directories (i.e. '/src', '/src/classes', etc.).  It is enabled for the project root directory context menu.

Was this planned?

Thanks for the help.

Cheers!

**Comment by vazexqi** [comment]
G'Day @ImJohnMDaniel 

I thought it makes sense for things that affect project level settings to be only available on the project directly and not on the sub folders.

With that in mind, did you detect any inconsistencies among the right-click menus?

**Comment by ImJohnMDaniel** [comment]
@vazexqi 

Your thought process makes sense.  Having said that, I would have preferred the option to be completely removed verses simply having it deactivated.  That way it avoids confusion.

Is there a use case to leave the option disabled verses removing it completely in the context menus "sub-project root"?
