### ISSUE TITLE
[BUG] 'Refresh from Server' does NOT update the meta information version. 

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#120]
Meta information does not update the version number when doing refresh from server, a package was updated yet the meta information is still showing an old version. 

Manually deleting the version information `packageVersions` node and 'Saving to Server' the class/page DOES update the meta information with right information. But deleting the information node and refreshing from server returns the old version still 

This experience is very problematic when you have multiple orgs, and your dev org has a managed package that is being updated as well. You QA might have never had the older version of the package and pushing to it results with an error due to version specified in 'meta' being older. 

![image](https://cloud.githubusercontent.com/assets/273413/8316290/f2517cf8-19c3-11e5-97d5-055ef3fc6881.png)

**Comment by danielsokolowski** [comment]
Looks like SF is 'caching' old version of the package so that older classes can still function which makes sense.

Rather then the manual process of deleting the `packageVersions` perhaps we need an explicit right click option to 'upgrade/re-link' classes against latest package version?

**Comment by vazexqi** [comment]
@danielsokolowski How did you determine that SF is 'caching' the old version of the package?

**Comment by danielsokolowski** [comment]
Hey @vazexqi, I am just guessing what is happening in the black box that is SF based on the following:

- worked on ocms_FooBar when our OCMS pagckage was 7.44
- meta information was referencing 7.44
- updated to 7.89, meta information ofcourse remained at 7.44
- fired up QA and deployed 7.89 to it

During push/deploy/(didn't try changeset) `ocms_FooBar` errors out with Package Version number does not exist, so tried the following:

- delete `packageVersions` from meta for ocms_Foobar and refreshed from server
- it re-updates with 7.44
- deleted `packageVersions` again and SAVED to server
- packageVersions is now what the latest is installed in the org i.e. 7.89

Other important things that gave me a gray hair (see bug https://github.com/forcedotcom/idecore/issues/66):

- changed packageVersions to 7.89
- selected files and choose to deploy them - the synchronize with server kicks in changes my packageVersion to 7.44
- deployment fails again with version missmatch

Another thing I just tested
- changed packageVersions of ocms_Foobar to 7.44 and pushed it to our DEV org, no issues - so I think there is a combiled 'old' 7.44 sitting there somewhere
- if I change it to 7.35 it errors out 'Description	Resource	Path	Location	Type
Save error: The specified Package Version number does not exist for that Package: cms, 7.35'

Would you know what to search for in SF docs regarding this observed behavior?

**Comment by danielsokolowski** [comment]
So I think possible options are:

-  do not store the `packageVersions` in our meta information which I don't think is possible because this is pulled from the server (can anyone confirm if this is what MavensMate does?)
- we add a right click option to update meta information to latest package version, this way we can do it in bulk.

Now that I understand the issue I advised the team of below procedure:

- pull all latest code from repo to ensure I have up to date code
- do a global replace of all the meta files using negative regex lookahead:
```
<packageVersions>\R        <majorNumber>7</majorNumber>\R        <minorNumber>((?!89).)*?</minorNumber>\R        <namespace>cms</namespace>\R    </packageVersions>
```
- replace to the text to use latest version
- push all files to repo again
