### ISSUE TITLE
Auto formatting code

### ISSUE THREAD

**Issue by sfdcnoob** [forcedotcom/idecore#123]
Hi @vazexqi,

Could you please implement the Auto format code feature. The Developer console provides the option to auto-format the code but it would be great if Force IDE also provides.

**Comment by andrew-chiz-muzychuk** [comment]
+1

**Comment by ram4ufriends** [comment]
I thought beta plug-in had automformat, am I wrong?

**Comment by vazexqi** [comment]
@ram4ufriends - No there isn't any autoformatting yet. We are aware of this issue and will consider implementing it.

**Comment by aleramesh** [comment]
@vazexqi  Can we expect single line and multi line comment keyboard shortcuts like we do for java classes?

**Comment by ram4ufriends** [comment]
@vazexqi..thanks, Sorry I confused with auto complete. Auto complete is available in beta version right?
