### ISSUE TITLE
Beta-Version-34.0.0.20150511 - No Unit Test coverage

### ISSUE THREAD

**Issue by gwickman** [forcedotcom/idecore#125]
This is very important so please put it back in. Great that you can run individual tests but we need the test coverage.
Also, right-click running of a single test class was very productive.

**Comment by andrew-chiz-muzychuk** [comment]
+1
That is why I roll back to 33

**Comment by DatGuyJonathan** [comment]
Fixed in v36: https://developer.salesforce.com/docs/atlas.en-us.200.0.eclipse.meta/eclipse/runTests.htm

**Comment by danielsokolowski** [comment]
Thanks @DatGuyJonathan
