### ISSUE TITLE
Using Beta v34 to edit package.xml produces error

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#126]
Hey @vazexqi 

When I edit the package.xml directly using the v34 BETA on the latest MARS JEE IDE, I see the editor is showing an error.  It is one of those small red indicator "flags" at the line number of the error.  The message reads:

Multiple annotations found at this line:
	- cvc-elt.1: Cannot find the declaration of element 
	 'Package'.
	- Start tag of element <Package>

In the past, when I edit a package.xml file, I have been able to type CTRL-SPACE and the editor will auto suggest the appropriate XML tags for that region.  At the <Package> tag level, it would usually suggest options like <types>, <versions>, etc.  At the <types> level, it would suggest <name> and <members> tag.  That functionality is no longer functioning.

I have checked the workspace log files but there is no error listed.

Any thoughts?

**Comment by vazexqi** [comment]
Fix is in the works.

**Comment by DatGuyJonathan** [comment]
Fixed in Beta v37.
