### ISSUE TITLE
Permission needed to download components

### ISSUE THREAD

**Issue by ram4ufriends** [forcedotcom/idecore#127]
Hi, What all permission needed to download code from IDE? Is it API Enabled permission? Can we have permission just to download the components but not modify?

**Comment by vazexqi** [comment]
@ram4ufriends I think those kinds of questions are more suitable for the [Developer Forums](https://developer.salesforce.com/forums/ForumsCategories) or [Salesforce StackExchange](http://salesforce.stackexchange.com/).

The issue queue is to report issues specific to the IDE.
