### ISSUE TITLE
[BUG] missing metadata selection of custom fields for standard/custom objects (version: 33.0.0.201504091124)

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#128]
In a change set I am able to select custom fields on a standard or custom objects however in Eclipse Force.com I can only select the entire object - there is no option to expand the object.

![image](https://cloud.githubusercontent.com/assets/273413/8923628/2ab27468-34c1-11e5-9fb4-7715fed58f8b.png)

I recall this was an option in the past...quick search does confirm this: http://salesforce.stackexchange.com/questions/57203/deploy-custom-fields-from-one-org-to-another-org

Installed version:   Force.com IDE  33.0.0.201504091124 com.salesforce.ide.feature.feature.group    salesforce.com

**Comment by mserran1** [comment]
Same problem here, happening on Windows7 x64, for IDEs 33 and 36, on Eclipse Juno and Neon.
I think this problem started on installation of Java8 JDK once it became mandatory for APEX Data Loader. 
Any special instructuons on how to make the IDE work with Java8?
