### ISSUE TITLE
Just a Thank You

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#130]
Noticed this just now - custom System.debug are added to a separate window in the test runner and anonymous apex

Thank you for improving Force.com IDE.

![image](https://cloud.githubusercontent.com/assets/273413/8964417/77abe050-35f3-11e5-89f3-664924901ffe.png)

**Comment by vazexqi** [comment]
@amgad-souleiman contributed this feautre in #65

**Comment by danielsokolowski** [comment]
http://www.jibjab.com/view/7W3MwZQtSKK5qIP97BJtMw?utm_campaign=URL+Copy&utm_content=well_done_clap&utm_medium=Share&utm_source=JibJab&cmpid=jj_url
