### ISSUE TITLE
Please add keyboard shortcut for commenting single line or multi line

### ISSUE THREAD

**Issue by sfdcnoob** [forcedotcom/idecore#131]
@vazexqi 
Could you please add the keyboard short cut feature to comment both single line and multi line code block.

**Comment by aleramesh** [comment]
@vazexqi, Can we expect this also in v36.0?

**Comment by vazexqi** [comment]
Unfortunately no. This one is a bit more involved so our team needs to decide if this is going to be on our roadmap. Over the next few weeks or so, our new team member @gwestersfdc will be unveiling more about our roadmap for the Force.com IDE in 2016.

**Comment by RichPorter01** [comment]
I have wanted this feature forever.  I just noticed that when editing a .page or .object file the normal shortcut works for commenting (i.e. Ctrl+Shift+/) and uncommenting (Ctrl+Shift+\), however it doesn't work on .cls files. I am using:

Force.com IDE	36.0.0.201601221512
Eclipse IDE for Java Developers   2.0.2.20140224-0000
Version: Kepler Release
Build id: 20130614-0229
