### ISSUE TITLE
Highlight all words which match selected word?

### ISSUE THREAD

**Issue by aleramesh** [forcedotcom/idecore#132]
Please add the feature to highlight all words which match selected word.

Here is the screenshot.
<img width="802" alt="autohighlight_matching_words" src="https://cloud.githubusercontent.com/assets/11079913/9158863/fdeb51f4-3eeb-11e5-8655-392ae7f2c48e.png">

**Comment by andrew-chiz-muzychuk** [comment]
Glance is good stuff, which I use for this purpose.

**Comment by aleramesh** [comment]
@andrew-chiz-muzychuk , Thanks so much for the suggestion. I started using this and love it :)
