### ISSUE TITLE
v34 release date?

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#133]
G'Day @vazexqi and @kaplanjosh 

Is there any update that you can give for when v34 will go GA or when a new v34 beta will be released?

Cheers!

**Comment by ImJohnMDaniel** [comment]
ping to @vazexqi and @kaplanjosh

**Comment by kaplanjosh** [comment]
We will not release any official plugin with v34 as its most recent version. There will be a new version available next month with v35 as its most recent version.

**Comment by ImJohnMDaniel** [comment]
@kaplanjosh - Thanks for the update.  Cheers!
