### ISSUE TITLE
Apex Test Runner layout and behaviour

### ISSUE THREAD

**Issue by andrew-chiz-muzychuk** [forcedotcom/idecore#134]
When you open Apex Test Runner tab, where you want to check results of running tests, it hides on each mouse click. You click on triangle near test class name to expand test methods - hide. Click on test method - hide. Click on System Debug Log - hide.
Here is a video, of what frustrates me - https://goo.gl/Noqaqd

Also, layout frustrates a bit.
![apextestrunner_layout](https://cloud.githubusercontent.com/assets/876879/9269981/bc72a680-4276-11e5-82fa-d8a5539cea57.jpg)
There is no comfortable way to change Log Level.

No code coverage is displayed.

Windows 8.1 64, Eclipse Mars, Force.com v.34

--
Best regards,
Andrew

**Comment by DatGuyJonathan** [comment]
Hi Andrew,

Thanks for voicing your concerns. We've had customers request that clicking on a test class/method takes them to the source code so they can find tests faster. The way those customers, and also myself, set up the Eclipse IDE is by splitting the window into multiple views. For example, you could have the Package Explorer on the left, Apex Test and Execute Anonymous views at the bottom, outline view on the right, and source code in the middle. See screenshot below:

![eclipseidesetup](https://cloud.githubusercontent.com/assets/7286437/9532282/85f124c6-4cbf-11e5-944e-6c3922ccec89.png)

With the IDE configured like that, you could select a test result without losing the Apex Test view. Please give that a try.

Regarding the layout, we've made changes to the Log Levels and they should be at a more convenient location. These changes will be in the official Force.com IDE v35 release.

Let us know if you encounter any more issues.

Regards,
Jonathan

**Comment by andrew-chiz-muzychuk** [comment]
That is a good idea. I'm ok with it. But it doesn't work in my case.
However, I in Mars release it just go to file, but not to specific method I select in Apex Test Runner tab.
I'll try this method on Luna and post my results here.

**Comment by DatGuyJonathan** [comment]
Ah yes, that bug is fixed in the upcoming v35 release. Soon, when you click on a test method in the test results, it will take you to the source code of the test method.
