### ISSUE TITLE
Any way to download v34?  

### ISSUE THREAD

**Issue by triestelaporte** [forcedotcom/idecore#138]
The main Force.com IDE channel has v33, the beta channel has v35.  My PDE is reliant on v34 metadata, and does not yet support v35.  Is there a place to get v34 still?

**Comment by triestelaporte** [comment]
I found an old copy of the v34 plugin jars on an old machine.  I am out of trouble for now.

**Comment by vazexqi** [comment]
@triestelaporte I've also added back v34 to the beta site.

**Comment by triestelaporte** [comment]
Even better!  Thanks!

On Fri, Sep 11, 2015 at 6:11 PM, Nick Chen <notifications@github.com> wrote:

> @triestelaporte <https://github.com/triestelaporte> I've also added back
> v34 to the beta site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forcedotcom/idecore/issues/138#issuecomment-139694905>
> .
>



-- 
Trieste LaPorte
Technical Architect
_______________________________
we are hiring! <http://codescience.com/careers>
CHATTANOOGA | ATLANTA | SAN FRANCISCO

*O:* 423.954.7400

*D: *503.200.4129

*F*: 901.654.7097

*codescience.com  <http://codescience.com/>*

**Comment by triestelaporte** [comment]
@vazexqi They're all there now!  Thanks.
