### ISSUE TITLE
Edit and deploy contents of static resources

### ISSUE THREAD

**Issue by TehNrd** [forcedotcom/idecore#14]
Inside the IDE static resources should look like any other normal file directory. You should be able to create hierarchy of files (text,binary,whatever) and edit these directly in the IDE. Then when you save it should automatically build the static resource and deploy it.

This is really important as more apps move back to the client and are very JavaScript heavy. This would also help with version control of the content inside the static resource as locally it would be the actual files, not just a big binary zip.

**Comment by GradyD** [comment]
@vazexqi This would be awesome if you could get it merged in.
