### ISSUE TITLE
Unable to fetch and save Force.com components to project

### ISSUE THREAD

**Issue by prolayc** [forcedotcom/idecore#140]
![image](https://cloud.githubusercontent.com/assets/5306583/10214098/8ec5fbec-6832-11e5-8aca-a6907f09cbe8.png)

I am using Eclise Juno SR2 with Java 8 SDK

**Comment by vazexqi** [comment]
@prolayc 

* What version of the IDE are you using, e.g., v32, v33?
* What version of your organization are you connecting to?
* What component(s) are you trying to retrieve?

**Comment by prolayc** [comment]
I am using the Force.com IDE version v33
I am connecting to the Unlimited version of Salesforce Org.
I have tried with the following options -
a) Apex and Visualforce
b) Selected Metadata Components

**Comment by vazexqi** [comment]
"I am connecting to the Unlimited version of Salesforce Org" <- what version (e.g., Summer '15 or Winter '16) is this org on?
"Apex and Visualforce" <- just selecting that also gives you the same error of invalid content lengths set?

**Comment by prolayc** [comment]
The Salesforce Org version Summer'15. 

Just selecting the "Apex and Visualforce" and also the selected Metadata Components, it is taking very long time and and giving the same error

![image](https://cloud.githubusercontent.com/assets/5306583/10225539/e0186374-6880-11e5-8bc4-77dd71952ece.png)

**Comment by vazexqi** [comment]
Do you the ability/permission to create cases with Salesforce support directly? I want to ask for some more sensitive information such as org id and user id that I'm not sure I am comfortable showing in public.

**Comment by prolayc** [comment]
No Nick. I donot have the permission to create the Salesforce support ticket.

**Comment by prolayc** [comment]
Are there any special permissions required for Sandbox org?

**Comment by vazexqi** [comment]
There seems to be something similar here at https://developer.salesforce.com/forums/?id=906F0000000AzWbIAK

Can you try to narrow it down to just apex classes and triggers to see if the issue occurs? Then slowly add other components so that we can identify which one is causing the issue?

**Comment by prolayc** [comment]
Thank you, Nick. The culprit was the static resources. I am able to download everything except the static resources. This helps.
