### ISSUE TITLE
Run Configuration icon not shown if "Package Explorer" view minimized

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#141]
The "Run Configuration" icon not shown if "Package Explorer" view minimized.  This becomes an inconvenience because, without access to that icon, I cannot setup or execute a unit test.

Eclipse Version: Mars Release (4.5.0) - Build id: 20150621-1200
Force.com IDE v34.0.0.201505141452

**Comment by vazexqi** [comment]
@ImJohnMDaniel  I can't reproduce. Here's what it looks like with my Package Explorer minimized.

![screen shot 2015-10-13 at 10 48 55 am](https://cloud.githubusercontent.com/assets/54414/10463248/4f16ed66-7198-11e5-9c0e-ae2cc9631557.png)

I am using Mars (albeit version 4.5.1) and v34 of the plug-in from http://media.developerforce.com/force-ide/beta

**Comment by ImJohnMDaniel** [comment]
@vazexqi I see what you mean.

The only other difference was that I had a couple of Apex class files open in the editor.  Your image doesn't show that.  Can you try that variation please?

**Comment by vazexqi** [comment]
![screen shot 2015-10-13 at 11 14 10 am](https://cloud.githubusercontent.com/assets/54414/10463879/dcba3454-719b-11e5-8b74-0a13a405d774.png)

I just noticed that you have an older version of the v34 plug-in. Can you update using the beta site?

**Comment by ImJohnMDaniel** [comment]
@vazexqi I just upgraded and no longer see the issue.  Thanks for the help.  Cheers!
