### ISSUE TITLE
Eclipse Choose Initial Project Contents Error

### ISSUE THREAD

**Issue by johnc847** [forcedotcom/idecore#142]
I just got a new laptop and trying to get Eclipse up and running again. When I go to create a new project and enter my credentials and click Next, it says fetching and then I get this screen. Any help would be appreciated.

If I just click Finish, it downloads what is normally the first radial button, Classes, Components, Pages, Static Resources and Triggers. 

![eclipse contects empty](https://cloud.githubusercontent.com/assets/12277563/10466476/79a747d6-71c2-11e5-96ce-af3443b5c934.png)

**Comment by vazexqi** [comment]
This has something to do with large fonts and the UI for that dialog not dynamically sizing.

You can do two things (for now):
1) maximize that window
2) reduce your font size

**Comment by johnc847** [comment]
Thank you!
