### ISSUE TITLE
v35 ''unexpected element. Parser was expecting..' error 

### ISSUE THREAD

**Issue by Scolliverius** [forcedotcom/idecore#143]
Error occurs when using schema and when creating triggers.
This makes neither of these tools available in the ide
What's the solution? - please include any relevant step by step actions.
thanks

**Comment by WellRedPandit** [comment]
Same here when opening salesforce.schema
![selection_006](https://cloud.githubusercontent.com/assets/3659381/10637500/043b9318-77d4-11e5-986f-8c77d787ee37.png)

**Comment by vazexqi** [comment]
Acknowledged. A fix is in the works and I'll push something to the Beta channel by this afternoon.
Please see [this](https://github.com/forcedotcom/idecore/wiki/Downloading-the-Beta-Version-of-the-Force.com-IDE) page on how to update from the beta channel.

**Comment by vazexqi** [comment]
@Scolliverius, @WellRedPandit - I've pushed a fix to the beta channel. Please try it out and let me know if that fixes your issues. I'll push to the main update site soon.

**Comment by Scolliverius** [comment]
@vazexqi Thanks this fixes the issue. Please do let us know when its pushed to the main site.

**Comment by WellRedPandit** [comment]
@vazexqi Confirming that it works in beta. Many many thanks!
Please do kindly let us know when it's available as a release.

**Comment by vazexqi** [comment]
I'll push it to the main site this afternoon.

**Comment by WellRedPandit** [comment]
@vazexqi Updated from the main site. Confirming it works. Thank you VERY MUCH for the quick turnaround on this!!!
