### ISSUE TITLE
please add bookmark feature

### ISSUE THREAD

**Issue by deterdangler** [forcedotcom/idecore#144]
@vazexqi ,

When working on large file with thousands of line, we need the ability to bookmark code blocks as mentioned in the below link:

[Eclipse bookmark feature](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2FgettingStarted%2Fqs-37-3c.htm)

**Comment by aleramesh** [comment]
Can we expect this feature in the next release?

**Comment by vazexqi** [comment]
@aleramesh - Yes. The next release for v36.0 is going out by next Friday.

**Comment by aleramesh** [comment]
@vazexqi Great!
