### ISSUE TITLE
Password is not stored

### ISSUE THREAD

**Issue by andrew-chiz-muzychuk** [forcedotcom/idecore#145]
1. Create project
2. Download by default (classes, triggers...)
3. New -> Apex Class
4. ![unabletocheckapexclasspermissions](https://cloud.githubusercontent.com/assets/876879/10883628/52b822cc-8184-11e5-9376-8eab6c1813d5.png)
5. Go to Project settings - no password
6. Enter password
7. Try to create a class - the same - wrong login/password
No difference between Eclipse versions or Force.com plugin. It stopped working in Windows. However, in Ubuntu everything works fine.
I tried with and without token.
I updated eclipse mars on Friday and on Monday neither Eclipse work. I installed fresh eclipse, plugin - doesn't work in Windows.

**Comment by vazexqi** [comment]
I recall that this has happened before. Could you try https://salesforce.stackexchange.com/questions/19366/force-com-ide-isnt-storing-passwords

The way passwords are stored are OS-specific.

**Comment by andrew-chiz-muzychuk** [comment]
You are totally right.
Thank you!
