### ISSUE TITLE
How to exclude managed packages in Force IDE?

### ISSUE THREAD

**Issue by sfdcnoob** [forcedotcom/idecore#147]
@vazexqi ,

Can you help me on how to exclude managed packaged being refreshed in Force IDE?

Whenever I right click on my project in Force IDE and select refresh from server then it takes considerable amount of time. I guess the reason is it is trying to refresh even the managed package apps, classes and pages from server but I am interested in refreshing only unmanaged classes, pages, components and etc.

Below is the package.xml file for my project in force IDE:

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>33.0</version>
</Package>
```

Below is the screenshot showing managed packages in Force IDE:

![Image of Force IDE showing managed packages](http://i.stack.imgur.com/dtpJi.png)

I also went into Add/Remove metadata components section to remove managed package components but nothing is selected to uncheck:

![Image of Force IDE showing metadata components](http://i.stack.imgur.com/1Ldll.png)

If nothing is present in package.xml and add/remove metadata components then why is it downloading managed packages to Force IDE??

**Comment by a7744hsc** [comment]
This issue is really a big trouble for me when trying to use force.com ide. Could you prioritise this or give a workaround? 

Thanks.

**Comment by gurditta** [comment]
Hi Guys,

Did you guys resolve this??? @a7744hsc any alternative solutions you took to resolve this?

**Comment by MartinSpamer** [comment]
I can tell git to ignore the Salesforce files, I cannot tell Salesforce to ignore the Git files.

Professional developers need keep their code files under source control.  The Salesforce IDE really **needs** an equivalent to git ignore file, to tell it to not attempt to upload the reference packages by default and to ignore local files for source control, like the .gitignore and README.md files.

This is a serious shortcoming in the IDE for professional developers.
