### ISSUE TITLE
[ANN] Salesforce disabling TLS 1.0 and what this means for the Force.com IDE

### ISSUE THREAD

**Issue by vazexqi** [forcedotcom/idecore#148]
Starting in the first quarter of calendar year 2016, Salesforce will begin disabling the TLS 1.0 encryption protocol. This phased approach will prevent it from being used to access the Salesforce service within inbound and outbound connections.

If you use Java 7, you won't be able to create or edit projects using the Force.com IDE plug-in for Eclipse unless you disable TLS 1.0. (TLS 1.0 is disabled by default in Java 8.) Update your eclipse.ini file to include this line.

-Dhttps.protocols=TLSv1.1,TLSv1.2

The location of the eclipse.ini file depends on your operating system. For more information, see https://wiki.eclipse.org/Eclipse.ini.

If you use Java 8, you do not need to make any changes.
 
For information about Salesforce’s timeline for disabling the TLS 1.0 encryption protocol, see https://help.salesforce.com/apex/HTViewSolution?urlname=Salesforce-disabling-TLS-1-0&language=en_US

**Comment by DatGuyJonathan** [comment]
https://github.com/forcedotcom/idecore/wiki/Changes-in-Force.com-IDE-Beta-Version-37.0.0.20160512
