### ISSUE TITLE
Not able to run test from force.com ide after updating to latest winter 16 release

### ISSUE THREAD

**Issue by santoshraman** [forcedotcom/idecore#149]
Hi,
After updating to latest force.com ide in eclipse, I'm no more able to run test class.
I tried to run test class from run configuration its keep giving me error "Unable to start test run" - "Try running the test again. If that doesn't work, run the test fromm Apex Test Execution in Step or from the Developer Console."
![image](https://cloud.githubusercontent.com/assets/1967898/11349879/87e4b446-91e3-11e5-8dd2-c9082a49c9a7.png)

**Comment by DatGuyJonathan** [comment]
@santoshraman , I'd like to get more details that led up to the error.

Was the test run asynchronous or synchronous?
Did you have Log Levels enabled in the Apex Test config?
Were you executing one test class or all test classes?
If you were executing one test class, were you executing one test method or all test methods?

You could also take a screenshot of the Apex Test config and post it here, and that should answer all the questions above.
