### ISSUE TITLE
Test run issue - lines not executed no longer listed

### ISSUE THREAD

**Issue by BryanLL** [forcedotcom/idecore#150]
When I configure a test run and execute, the lines NOT executed are no longer listed. This was critical in helping increase code coverage. Is there a way to get this information that just isn't set by default? If not, can this be added again, please???

P.S. I'm at v 35.0.0.201510211056

**Comment by DatGuyJonathan** [comment]
Hi @BryanLL ,

Thanks for your feedback! I'd like to get some more of your input on this feature.

In Apex Test Results view, there is a Code Coverage panel. That panel will list your Apex classes, percent covered, and lines covered & total lines. For each class that is not 100% covered, would you want a dropdown that opens another row which will list all the lines not covered in that class? Would you rather have the info in a different column? In a different panel? Do you want to be able to copy & paste this list of uncovered lines? Any other thoughts on the placement of this info?

Let us know, thanks!

**Comment by BryanLL** [comment]
It used to drop down under the class name, I believe. I think having it either drop down under the class name like it used to or have it pop up in a new window would be fine.

**Comment by prudev** [comment]
I'd like to see it work like the developer console.  When you click on the class, bring the class up and highlight those lines covered in green and those not covered in red.  but I agree with Bryan that having the ability to see which lines are not covered is critical functionality to the force.com developer.

**Comment by BryanLL** [comment]
I don't mind how the developer console one works, but it seems the highlighting goes away with any kind of click in the source, so it's not ideal. But that concept is great.

**Comment by danielsokolowski** [comment]
+1 to have Eclipse display coverage the same way it work in the 
Salesforce Developer Console

On 12/7/2015 4:15 PM, BryanLL wrote:
>
> I don't mind how the developer console one works, but it seems the 
> highlighting goes away with any kind of click in the source, so it's 
> not ideal. But that concept is great.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/forcedotcom/idecore/issues/150#issuecomment-162665927>.
>


-- 
Daniel Sokolowski
Danols Web Engineering
http://webdesign.danols.com/
Office: 613-817-6833
Kingston, ON K7L 1H3, Canada


Notice of Confidentiality:
The information transmitted is intended only for the person or entity to which it is addressed
and may contain confidential and/or privileged material. Any review re-transmission dissemination
or other use of or taking of any action in reliance upon this information by persons or entities
other than the intended recipient is prohibited. If you received this in error please contact
the sender immediately by return electronic transmission and then immediately delete this
transmission including all attachments without copying distributing or disclosing same.

**Comment by DatGuyJonathan** [comment]
We're looking into this. Thanks for letting us know!

**Comment by DatGuyJonathan** [comment]
Fixed in Force.com IDE Spring '16

https://developer.salesforce.com/page/Force.com_IDE_Release_Notes#Enabled_code-coverage_highlighting_in_Apex_classes

**Comment by BryanLL** [comment]
Works great! Thanks!!!
