### ISSUE TITLE
Test run issue - Class and methods not always listed

### ISSUE THREAD

**Issue by BryanLL** [forcedotcom/idecore#151]
Some of my test runs don't show the class and methods that were run in the results. I don't see any difference between this configuration and another one that _does_ show the class & methods, except it's for a different test class.

![testconfignoclassnomethodlisted](https://cloud.githubusercontent.com/assets/7180669/11565080/5e030cee-99aa-11e5-849b-49b4264f643e.jpg)
![testresultsnoclassnomethodlisted](https://cloud.githubusercontent.com/assets/7180669/11565083/60aa448a-99aa-11e5-83c1-7af0d11d790c.jpg)

P.S. I'm at v 35.0.0.201510211056

**Comment by DatGuyJonathan** [comment]
@BryanLL , did you save to server and verified there were no compilation failures?
