### ISSUE TITLE
Deploy to Server action missing or not working from context menu

### ISSUE THREAD

**Issue by prudev** [forcedotcom/idecore#153]
I used to be able to right-click within an Apex class or Visualforce page tab to deploy that asset to another server.  That pick is no longer available for Apex classes and while available for a Visualforce page, does nothing.  Now I have to do this from within the Package Explorer.  Can you restore this functionality please?

**Comment by DatGuyJonathan** [comment]
Quick question @prudev . Is the concern here that it takes more time that necessary to find the single asset you want to deploy in the Package Explorer?

**Comment by prudev** [comment]
The concern is that it used to very easy to deploy a single asset from one sandbox to another.  Now I have to find the thing in the package explorer.  It just adds time to an already tight day.  I don't understand why this capability was removed in the first place.

**Comment by vazexqi** [comment]
Deployment is meant for bulk changes from one org to another. If you are doing fine-grained changes, and want to save frequently to that org, you should attach the Force.com project to that org itself.

There is a viable workaround. If you are having a hard time locating the single asset, you can try

1. Apple + Opt + W to reveal in the package explorer.
1. Link with Editor button on the package explorer.
