### ISSUE TITLE
Apex Test Results Code Coverage incorrect (and mouse-click issue)

### ISSUE THREAD

**Issue by BryanLL** [forcedotcom/idecore#154]
I just ran a test class that completed successfully. It invokes a half-dozen methods in the class I'm testing, but the code coverage for that class shows 0/90 lines executed for that class. I suspect it's showing the coverage from the last time I ran all tests, not this particular run. It would also be great if the code coverage panel showed which classes were tested from the test run (maybe show the code coverage class in green if it was tested and had 75% from this run; yellow if tested and < 75% coverage; leave black for untested by this test run.

Also, though minor, I keep the "Problems, Apex Test Results, Execute Anonymous, etc" panel minimized, and in the test results pane where the test classes and methods are listed, when I click the expand button/triangle on the test class I ran the screen jumps to the class, closing/hiding the test results. I like this feature for when I click on the class or method name, but not for the expand button/triangle.
--Bryan

**Comment by BryanLL** [comment]
Update - it seems I don't get the test result lines executed count when logging is not enabled. When I turn on logging, then the code coverage panel shows the line count.

**Comment by DatGuyJonathan** [comment]
We will fix the expand triangle issue. Thanks for letting us know!

@BryanLL , as for the first issue, it sounds like you ran all tests, got 0/90 lines for that one Apex class, wrote tests for it, ran just the new tests, and code coverage still showed 0/90 lines.  Is that the right sequence of events? Were your code changes saved to server?

**Comment by BryanLL** [comment]
@DatGuyJonathan, yes, that's the sequence of events. Once I enabled logging in the run configuration then it seemed to work properly.
