### ISSUE TITLE
Force.com IDE 36 | Refresh or sync single CustomObject / metadata-file does not work and the content is replaced with empty tag

### ISSUE THREAD

**Issue by anterokarttunen** [forcedotcom/idecore#159]
Force.com IDE 36.0.0.201601081632

This does not happen when you do the refresh / sync from folder or project level.

1 Refresh or sync user.object 
2 Fails with these errors and user.object content is empty & contains only this

`<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata"/>`

error log entry 1

eclipse.buildId=4.3.2.M20140221-1700
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/xxxx/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -data /Users/xxxx/Documents/xxxx/force-workplace -product org.eclipse.epp.package.jee.product -keyring /Users/xxxx/.eclipse_keyring -showlocation

Warning
Thu Jan 14 18:20:35 EET 2016
 WARN [2016-01-14 18:20:35,937](ProjectService.java:handleRetrieveMessages:2176) - Unable to handle retrieve message - could not find component 'package.xml' for message 'Entity type: 'StandardObject' is unknown'

error log entry 2

eclipse.buildId=4.3.2.M20140221-1700
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/xxxx/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -data /Users/xxxx/Documents/xxxx/force-workplace -product org.eclipse.epp.package.jee.product -keyring /Users/xxxx/.eclipse_keyring -showlocation

Warning
Thu Jan 14 18:20:35 EET 2016
 WARN [2016-01-14 18:20:35,937](ProjectPackageList.java:getComponentByMetadataFilePath:834) - Did not find component for 'package.xml'

**Comment by latentfuss** [comment]
I have the same problem with
Version: Kepler Service Release 2
Build id: 20140224-0627

**Comment by dangmai** [comment]
I have the same problem:

Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

**Comment by bcashen** [comment]
Same issue. 
Version: Mars.1 Release (4.5.1)
Build id: 20150924-1200

If I do a "Refresh from Server" on the src folder then the object metadata reappears but if I select just that one object and do a refresh I get:

<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata"/>

and nothing else.
 
This is what I have in the force-ide.log:
 WARN [2016-05-12 10:56:25,782] (ProjectPackageList.java:getComponentByMetadataFilePath:834) - Did not find component for 'package.xml'
 WARN [2016-05-12 10:56:25,788] (ProjectService.java:handleRetrieveMessages:2176) - Unable to handle retrieve message - could not find component 'package.xml' for message 'Entity of type 'CustomObject' named '' cannot be found'

**Comment by bcashen** [comment]
I should add, this happens regardless of the object I'm trying to refresh from the server.

**Comment by kentafujimoto** [comment]
I have same issue
when refresh standard/custom object metadata

<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata"/>

Eclipse IDE for Java Developers
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600
Force.com IDE Version:  36.0.0.201601221512

**Comment by rrd-pavala** [comment]
We just upgraded to force.com IDE version 36.0. and facing the same issue.

Any one resolved it?

**Comment by vazexqi** [comment]
If you are using Java 8, could you try the beta version of 37 from https://github.com/forcedotcom/idecore/wiki/Downloading-the-Beta-Version-of-the-Force.com-IDE (note that this only works with Java 8).

**Comment by rrd-pavala** [comment]
Thanks for the quick reply but i have Java version 7 :(

**Comment by kentafujimoto** [comment]
version 37 doesn't work well.
This problem occur yet.
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata"/>

my Mac's java ver is 
 java version "1.8.0_73"

**Comment by rrd-pavala** [comment]
Thanks Nick.

Looks like we need to have Mars version and java 8 otherwise version v37.0
may not work

Thanks & Regards,
Prasad Avala | Technical Analyst | RR Donnelley
314 Susan Drive |Normal,IL -61761 | Office:309-585-3269
Email: prasad.avala@rrd.com
