### ISSUE TITLE
Put informative error message if org's version is not compatible with Force.com plugin

### ISSUE THREAD

**Issue by andrew-chiz-muzychuk** [forcedotcom/idecore#160]
I run into this issue here - http://stackoverflow.com/questions/34880727/salesforce-error-returnfielddata-types-invalid-at-this-location-using-eclipse

When you try to create a new project using force.com error come up:
Unable to fetch organization details for 'username' Element {urn:partner.soap.sforce.com}returnFieldData Types invalid at this location

**Comment by chowwinston** [comment]
As mentioned in the stackoverflow link, this is because you are connecting with a newer version of the Force.com IDE to an older org. This will be resolved when the instances get upgraded.
