### ISSUE TITLE
Cannot select prior API version

### ISSUE THREAD

**Issue by BryanLL** [forcedotcom/idecore#161]
I've updated to version 36.0.0.201601081632. My development sandbox is Spring '16 (api 36.0) but my production org is not there yet. I cannot find a way in Force.com IDE to specify new classes, triggers, pages, etc. be created for 35.0 instead of 36.0. 

--Bryan

(P.S. It also seems I can no longer connect Force.com IDE to my production org and I assume it's because of the API version. I guess I can live with that until production catches up.)

**Comment by chowwinston** [comment]
Unfortunately this behavior is intended. When we roll out the new Force.com IDE we will try to include this feature. Stay tuned!
