### ISSUE TITLE
Force.com IDE 36 - "Upgrade Project" unable to connect to previously working org

### ISSUE THREAD

**Issue by up2go-rsoesemann** [forcedotcom/idecore#162]
I just upgraded my Eclipse from 35 to the latest 36. As with every update every projects asks for an Upgrade but this always fails with 

<img width="586" alt="bildschirmfoto 2016-01-22 um 17 14 43" src="https://cloud.githubusercontent.com/assets/8180281/12516048/aed8221e-c12b-11e5-9273-f31678d27f8a.png">

Eclipse was also not able to revert to the previous configuration. So I am stuck!

I think the problem is that none of my orgs is on Spring '16 yet. Can I still get my Eclipse working?

**Comment by vazexqi** [comment]
@up2go-rsoesemann  Yes, it's because your org is not on Spring '16 yet. See https://developer.salesforce.com/forums?id=906F0000000MKqFIAW for more information. You should be able to reinstall the older version.

**Comment by andrew-chiz-muzychuk** [comment]
Yes, the same here - https://github.com/forcedotcom/idecore/issues/160

**Comment by RenegadeCoder** [comment]
I thought there was supposed to be a feature several releases ago that would allow you to manually specify an older API version for exactly this reason. And yet, I have this problem every time there's a new release...

**Comment by chowwinston** [comment]
This is the same issue as #160 
@RenegadeCoder When we roll out the new Force.com IDE we will try to include this feature. Stay tuned!
