### ISSUE TITLE
[FEATURE] Allow selecting multiple classes in the new Apex Test Runner

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#163]
Right now the options are all classes, or just one class - please allow specifying a subset of test classes.

**Comment by DatGuyJonathan** [comment]
What are your thoughts on test suites?

http://docs.releasenotes.salesforce.com/en-us/spring16/release-notes/rn_apex_tests.htm#rn_apex_tests_test_suites

https://developer.salesforce.com/page/Force.com_IDE_Release_Notes

**Comment by danielsokolowski** [comment]
I'm on v35 until the org upgrades to v36 but from reading it looks like it would work. Are there plans to allow customization and editing of these right from Eclipse?

**Comment by vazexqi** [comment]
@danielsokolowski - Unfortunately, you cannot edit them from Eclipse as of v36. If you want a graphical editor, then you have to use the developer console for now. Or you can create them using the API through SOAP/REST.

As an open source idea, you (or someone) can probably create a quick tool that can parse a XML file and convert that to API calls to create a test suite on the server. To give you an idea, you might consider mirroring the structure that TestNG uses to specify test suites (http://testng.org/doc/documentation-main.html#testng-xml).

If you do make this contribution, it will be a nifty tool that we could include in the Force.com IDE.
