### ISSUE TITLE
"Drag, Drop & Upload Multiple Attachments" folder showing

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#165]
I set up a new project and specifically selected only the Apex Class files in the org.  When I checked out the source code locally, a new folder appeared in the /src folder (see image below) .   It was "Drag, Drop & Upload Multiple Attachments".   Based on the contents folder, it would appear to be one of the managed packages in the org.  There is a managed package by that name.

![defect](https://cloud.githubusercontent.com/assets/1149727/13399986/b2ff5748-ded3-11e5-87a1-5d5f82685fa9.png)

Is this some new feature that is coming out in the next release?

I am using Force.com IDE beta v36.0.0.201602191153

**Comment by vazexqi** [comment]
No, this is not a new feature. We'll investigate what is going on.

**Comment by chowwinston** [comment]
@ImJohnMDaniel  I'm not able to reproduce this issue. Is the folder structure of this the same as in "Referenced Packages"? 

I've never seen a managed package with so many subfolders. Which package did you install?

**Comment by guenthmn** [comment]
I am seeing the same problem in my source folder, it one of the most popular app exchange applications.

https://appexchange.salesforce.com/listingDetail?listingId=a0N30000008ZVcdEAG <https://appexchange.salesforce.com/listingDetail?listingId=a0N30000008ZVcdEAG>




Matthias Guenther

**Comment by ImJohnMDaniel** [comment]
@chowwinston - this particular managed package did not show up in the "Referenced Packages" folder.  Currently, I have nothing showing under that folder.
