### ISSUE TITLE
Turning on "Build Automatically" saves additional metadata to the server

### ISSUE THREAD

**Issue by janjulian** [forcedotcom/idecore#168]
When "Build Automatically" is turned on, the IDE seems to save-to-server metadata that I am not actively working on or do not intend on saving to server. As a result of enabling this action, the "Building workspace" pop-up sometimes appears, indicating to me that the IDE is saving something to the server, and then later on reports several "Save error: Conflict found while preparing to save..." problems. 

![image](https://cloud.githubusercontent.com/assets/2403043/13536853/fb46242a-e1f6-11e5-8f30-293606089b68.png)

This is very concerning especially for any metadata that is actually overwritten by the save-to-server process successfully. 

I'm not sure if there's a criteria to determine which set of metadata are saved (e.g., files modified in the last 5 minutes are saved to server?). Ideally, the action of enabling the "Build Automatically" should not execute a build (or save to server) immediately. Perhaps it can execute when a user saves a modified file (as it does so today). Likewise, when a project is connected to a git repository, it shouldn't execute a build on git operations (e.g., switching/resetting branches).

**Comment by vazexqi** [comment]
@jmrjulian 

1. Which version of the Force.com plug-in are you using?
1. What version of Eclipse IDE are you using?
1. What version of Java are you using?

Do you have a series of minimal steps to reproduce this issue? Or is this issue specific to your org? I think it could be a general bug but I just want to check.

**Comment by jmrjulian** [comment]
@vazexqi 

1. Force.com IDE 36.0.0.201601221512
2. Eclipse Java EE IDE for Web Developers. Mars.2 Release (4.5.2)
3. Java version "1.8.0_45"

I've noticed this behavior for a few releases of Force.com IDE and Eclipse as well. The most consistent repro steps requires connection to a git repo with at least 2 branches.

Requirements:
- Force.com project with some metadata setup in eclipse.
- Project connected to a git repo (with at least two branches that have metadata differences).
- Force.com project set to work online (not sure if related to issue but I always turn this on)

Steps to reproduce:
- Start/load IDE.
- Ensure "Build Automatically" disabled.
- Select git-connected force.com project, switch branches.
- Enable "Build Automatically".

Current behaviour:
- Enabling the setting executes the process.

Expected behavior:
- Process not executed.

**Comment by danielsokolowski** [comment]
Are you also working with eGIT or Mercurial? I wonder if it is the same 
issue I experienced here: 
https://github.com/forcedotcom/idecore/issues/76 and 
https://github.com/forcedotcom/idecore/issues/66#issuecomment-61109213 
which is the reason I have work offline enabled now and use save to 
server, or synchronize with server.

On 2016-03-04 2:13 PM, jmrjulian wrote:
>
> When "Build Automatically" is turned on, the IDE seems to 
> save-to-server metadata that I am not actively working on or do not 
> intend on saving to server. As a result of enabling this action, the 
> "Building workspace" pop-up sometimes appears, indicating to me that 
> the IDE is saving something to the server, and then later on reports 
> several "Save error: Conflict found while preparing to save..." problems.
>
> image 
> <https://cloud.githubusercontent.com/assets/2403043/13536853/fb46242a-e1f6-11e5-8f30-293606089b68.png>
>
> This is very concerning especially for any metadata that is actually 
> overwritten by the save-to-server process successfully.
>
> I'm not sure if there's a criteria to determine which set of metadata 
> are saved (e.g., files modified in the last 5 minutes are saved to 
> server?). Ideally, the action of enabling the "Build Automatically" 
> should not execute a build (or save to server) immediately. Perhaps it 
> can execute when a user saves a modified file (as it does so today). 
> Likewise, when a project is connected to a git repository, it 
> shouldn't execute a build on git operations (e.g., switching/resetting 
> branches).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/forcedotcom/idecore/issues/168>.
>

-- 
Daniel Sokolowski
http://danols.com/
Office: 613-817-6833
Kingston, ON K7L 1H3, Canada


Notice of Confidentiality:
The information transmitted is intended only for the person or entity to which it is addressed
and may contain confidential and/or privileged material. Any review re-transmission dissemination
or other use of or taking of any action in reliance upon this information by persons or entities
other than the intended recipient is prohibited. If you received this in error please contact
the sender immediately by return electronic transmission and then immediately delete this
transmission including all attachments without copying distributing or disclosing same.

**Comment by jmrjulian** [comment]
Cleaning the project (ie. Project > Clean... ) seems to prevent the automatic execution of the build when the setting is enabled.
