### ISSUE TITLE
QUESTION: Will Salesforce.com eventually port the Force.com IDE to Eclipse Che?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [forcedotcom/idecore#169]
When I learned about [the new Eclipse Che][1] I thought it would be a perfect-match for a 

 - modern browser- and cloud-based IDE for Salesforce.com
 - a replacement for the [prototypish Developer console][2]
 - easy to port from [existing Force.com IDE code][3]

Are there any plans at Salesforce.com investing in Che? 

*Please don't flag this. I know this is somewhat #SafeHarbour but I guess there is a lot of interest in the community about better IDE for Salesforce.*

  [1]: https://www.eclipse.org/che/
  [2]: https://success.salesforce.com/ideaView?id=08730000000iALkAAM
  [3]: https://github.com/forcedotcom/idecore

(clone of [http://salesforce.stackexchange.com/questions/113688/will-salesforce-com-eventually-port-the-force-com-ide-to-eclipse-che](http://salesforce.stackexchange.com/questions/113688/will-salesforce-com-eventually-port-the-force-com-ide-to-eclipse-che))

**Comment by gwestersfdc** [comment]
Our development team has not yet scoped the effort to bring Che compatibility for the Force.com plugin. We are investigating.
