### ISSUE TITLE
Question: Can we get community alerts on new beta and stable releases?

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#171]
Hey @vazexqi and @gwestersfdc 

I just happen to notice the newest beta release.  It got me to think if a dedicated Twitter account or some other community mechanism could be setup to announce when there are new releases; either stable or beta.  @SalesforceDevs twitter account could periodically let the community know by re-tweeting.

I, for one, want to work with the beta releases and I love it that you guys are starting to release them at steady pace.  It would be good though to get some sort of announcement when it occurs.

Anyway, just a thought.  Thanks for all of the hard work!

Cheers,

John

CC: @kaplanjosh

**Comment by vazexqi** [comment]
Yes, this is a wonderful idea. I'm not a big user of twitter so I'll defer to @gwestersfdc to handle this part.

**Comment by ImJohnMDaniel** [comment]
@gwestersfdc.  Is there any news on this one?  Cheers!

**Comment by danielsokolowski** [comment]
Would anyone know where can we see the latest changes for the latest beta? Sorry if I missed the obvious.

**Comment by ImJohnMDaniel** [comment]
@vazexqi and @gwestersfdc 

Any news on this front?

Any new beta build coming soon?

**Comment by vazexqi** [comment]
I've just pushed a beta version.

**Be sure to use Java 8 and Eclipse Mars. I've also updated the endpoints so you need to connect to an org that is already on v37.**
 
Release notes are available at https://github.com/forcedotcom/idecore/wiki/Changes-in-Force.com-IDE-Beta-Version-37.0.0.20160513.

We have not finalized on the twitter account yet.

**Comment by ImJohnMDaniel** [comment]
@vazexqi Thanks for the update!  Cheers!

**Comment by danielsokolowski** [comment]
Thanks for the update.
