### ISSUE TITLE
All the "package.xml" files under "Referenced Package" become read-only after refresh from server

### ISSUE THREAD

**Issue by chriswolf-afirmon** [forcedotcom/idecore#174]
After performing a Force.com "refresh from server" operation, all the `package.xml` files under `Referenced Packages` become read-only and thus subsequent refreshes fail to overwrite these.  I've seen this issue for years, now.  Thanks for looking and great tool.

```
OS Name:                   Microsoft Windows 8.1
OS Version:                6.3.9600 N/A Build 9600
Total Physical Memory:     8,106 MB
Available Physical Memory: 4,309 MB
Virtual Memory: Max Size:  9,386 MB
Virtual Memory: Available: 4,493 MB
Virtual Memory: In Use:    4,893 MB

Eclipse Java EE IDE for Web Developers.
Version: Mars.1 Release (4.5.1)
Build id: 20150924-1200

Force.com
Version: Winter '15 (35.0.0)
Copyright (c) 2005-2015, salesforce.com, inc. All rights reserved.
Version 35.0.0.201510211056

eclipse.ini
-vmargs
-Dhttps.protocols=TLSv1.1,TLSv1.2 
-Dosgi.requiredJavaVersion=1.7
-Xms512m
-Xmx4096m
```

**Comment by chriswolf-afirmon** [comment]
I just noticed that other file types under `Referenced Packages` also become read-only and thus not refreshable from server:

```
!SESSION 2015-12-16 04:35:47.158 -----------------------------------------------
eclipse.buildId=4.5.1.M20150904-0015
java.version=1.7.0_80
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

This is a continuation of log file C:\Users\cwolf\workspace\.metadata\.bak_0.log
Created Time: 2015-12-16 04:53:28.213

!ENTRY com.salesforce.ide.core 2 0 2015-12-16 04:53:28.213
!MESSAGE  WARN [2015-12-16 04:53:28,211] (ProjectPackageList.java:saveResources:1196) - Unable to save component 'CustomTab 'Conga Composer/tabs/Conga_Merge_Query__c.tab' [Conga Composer]' to File /Hillel-dev/Referenced Packages/Conga Composer/tabs/Conga_Merge_Query__c.tab is read-only. Cause:
 (1) File /Hillel-dev/Referenced Packages/Conga Composer/tabs/Conga_Merge_Query__c.tab is read-only.


!ENTRY com.salesforce.ide.core 2 0 2015-12-16 04:53:28.220
!MESSAGE  WARN [2015-12-16 04:53:28,220] (ProjectPackageList.java:saveResources:1196) - Unable to save component 'CustomTab 'Conga Composer/tabs/Conga_Setup.tab' [Conga Composer]' to File /Hillel-dev/Referenced Packages/Conga Composer/tabs/Conga_Setup.tab is read-only. Cause:
 (1) File /Hillel-dev/Referenced Packages/Conga Composer/tabs/Conga_Setup.tab is read-only.


!ENTRY com.salesforce.ide.core 2 0 2015-12-16 04:53:28.225
!MESSAGE  WARN [2015-12-16 04:53:28,225] (ProjectPackageList.java:saveResources:1196) - Unable to save component 'CustomTab 'Conga Composer/tabs/Conga_Template__c.tab' [Conga Composer]' to File /Hillel-dev/Referenced Packages/Conga Composer/tabs/Conga_Template__c.tab is read-only. Cause:
 (1) File /Hillel-dev/Referenced Packages/Conga Composer/tabs/Conga_Template__c.tab is read-only.


!ENTRY com.salesforce.ide.core 2 0 2015-12-16 04:53:28.232
!MESSAGE  WARN [2015-12-16 04:53:28,231] (ProjectPackageList.java:saveResources:1196) - Unable to save component 'ApexTrigger 'Conga Composer/triggers/CleanUpRecords2.trigger' [Conga Composer]' to File /Hillel-dev/Referenced Packages/Conga Composer/triggers/CleanUpRecords2.trigger is read-only. Cause:
 (1) File /Hillel-dev/Referenced Packages/Conga Composer/triggers/CleanUpRecords2.trigger is read-only
```

**Comment by chriswolf-afirmon** [comment]
I just looked at the code and see that setting the retrieved file to read-only is done "on purpose" - the question is why?  It's causing subsequent "refresh from server" to fail.

In `com.salesforce.ide.core.model.ComponentResource.setFileAccess()`, I see:
```
    private void setFileAccess(IFile file) {
        if (file != null && isInstalled()) {
            ResourceAttributes resourceAttributes = new ResourceAttributes();
            resourceAttributes.setReadOnly(true);
            try {
                file.setResourceAttributes(resourceAttributes);
            } catch (CoreException e) {
                String logMessage = Utils.generateCoreExceptionLog(e);
                logger.warn("Unable to set read-only on file " + resource.getName() + ": " + logMessage);
            }

            if (logger.isDebugEnabled()) {
                logger.debug("Set read-only access on " + file.getName());
            }
        }
    }
```

The question is why?

**Comment by vazexqi** [comment]
@chriswolf-afirmon Thanks for reporting the bug and the detailed analysis. 

I can answer the "why" we make the files in the "Referenced Package" read-only. The "Referenced Package" folder contains code for packages that you install and you can't modify. On my Mac, you can view them but when you try to make a change, it warns you that the file is read-only. This is why we mark them as read-only. Again, on my Mac, it doesn't seem to throw the error when it is refreshed, even if it is a read-only file. _So, I need to get hold on a Windows VM to repro you case_.

Now, in https://github.com/forcedotcom/idecore/issues/174#issuecomment-207889896 your error message was 

```
Root Exception: C:\Users\cwolf\workspace\demo\src\classes\unsubscribe.cls (Access is denied)
```

which is  a bit weird since src\classes\unsubscribe is not under the "Referenced Package" folder.  So are the files outside the "Referenced Package" also marked as read-only for you?

**Comment by iandrosov** [comment]
I get this problem on MAC as well but seem only if I Take defaults when downloading metadata initially. If I select what metadata I want in my project during initial create Eclipse IDE works correctly.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
