### ISSUE TITLE
No Conflicts Reported When Saving Code from Eclipse IDE.

### ISSUE THREAD

**Issue by pranavraulkar** [forcedotcom/idecore#175]
I again see that the IDE does not report any conflicts when the file has been changed by someone else. Steps to reproduce -
1. A creates a class from developer console or salesforce UI.
2. B creates project via eclipse(beta) and gets the new class.
3. B modifies class and saves it. Success.
4. A modifies the class from salesforce UI or dev console.
5. B tries to save his updates without taking a refresh, no conflict reported and overwrites changes by A.

I had reported a similar issue which was said to be resolved in beta channel. I'm not sure if it is or what's the plan on this. I had already reported this for an earlier stable version [here](https://github.com/forcedotcom/idecore/issues/66).

**Comment by AndyRouse42** [comment]
I'm experiencing the same issue. On the latest version of Eclipse (Neon) and latest version of the API (37)

**Comment by lcoffin** [comment]
Did it ever get really fixed? I was under the impression it never was... you still had to uncheck the 'Use Tooling API' setting to get the conflict detection working again -- that is enabled by default, so it doesn't check for conflicts by default.

Have you tried unchecking the 'Use Tooling API' option?

-L

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
