### ISSUE TITLE
[FEATURE] ApexDoc support

### ISSUE THREAD

**Issue by snugsfbay** [forcedotcom/idecore#176]
Please merge the code from the Salesforce Foundation open source ApexDoc project for easy doc support:
https://github.com/SalesforceFoundation/ApexDoc

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
