### ISSUE TITLE
[BUG?] Test  execution tabs are blank

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#177]
My test configuraiton does not use suites and just exeuctes one test class; un-tested code highlight does appear to work. 

I am on   Force.com IDE 36.0.0.201603220507 com.salesforce.ide.feature.feature.group    salesforce.com

![image](https://cloud.githubusercontent.com/assets/273413/15295034/b249cb88-1b5c-11e6-8d86-cdf01be4ccde.png)

Here is the test configuration

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration type="com.salesforce.ide.core.launch.RunTestsLaunchConfiguration">
<booleanAttribute key="enableLogging" value="true"/>
<booleanAttribute key="existingTf" value="false"/>
<stringAttribute key="forceComProjectName" value="REMOVED (Staging) [SBX]"/>
<stringAttribute key="forceComTestClass" value="ocms_stg_BlogControllerTest.cls"/>
<stringAttribute key="forceComTestMethod" value="(all methods)"/>
<booleanAttribute key="isAsync" value="false"/>
<mapAttribute key="logLevels">
<mapEntry key="Apex Code" value="DEBUG"/>
<mapEntry key="Apex Profiling" value="INFO"/>
<mapEntry key="Callout" value="INFO"/>
<mapEntry key="Database" value="INFO"/>
<mapEntry key="System" value="DEBUG"/>
<mapEntry key="Validation" value="INFO"/>
<mapEntry key="Visualforce" value="INFO"/>
<mapEntry key="Workflow" value="INFO"/>
</mapAttribute>
<booleanAttribute key="org.eclipse.debug.core.capture_output" value="false"/>
<booleanAttribute key="org.eclipse.debug.ui.ATTR_CONSOLE_OUTPUT_ON" value="false"/>
<stringAttribute key="suiteIds" value=""/>
<stringAttribute key="suiteJson" value="{&quot;suiteids&quot;:&quot;&quot;}"/>
<stringAttribute key="testsArray" value="{&quot;tests&quot;:[{&quot;classId&quot;:&quot;01pf00000003dKAAAY&quot;}]}"/>
<booleanAttribute key="useLogging" value="false"/>
</launchConfiguration>
```

**Comment by DatGuyJonathan** [comment]
@danielsokolowski , what happens when you run the same test class from Developer Console?

**Comment by danielsokolowski** [comment]
The first time it happened there was an exception that surfaced in Developer Console, after fixing it the end result was the same - no info populated but code coverage highlight showed more code covered.

**Comment by DatGuyJonathan** [comment]
I've seen something like this in the past and the user's code wasn't compiling correctly. The Developer Console & Force.com IDE test runner didn't understand how to display the compile errors. Do you have any compilation failures?

**Comment by danielsokolowski** [comment]
@DatGuyJonathan just tested, the file saves to server no problem so no compilation failures, anything else I can provide? We can do a join.me session.

**Comment by DatGuyJonathan** [comment]
@danielsokolowski , it would be helpful if I could get your organization ID and the test class ID that's causing the issue. Let me know the time (and timezone) and meeting ID for a quick join.me session.

**Comment by cfann61CW** [comment]
I'm experiencing this issue as well.  Were you able to find a solution?

**Comment by cfann61CW** [comment]
After fixing an unrelated class that had errors and was saved to the server, the issue was fixed

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
