### ISSUE TITLE
dark themes (syntax highlight) does not work for apex

### ISSUE THREAD

**Issue by vitaly-zdanevich** [forcedotcom/idecore#179]
I see correct syntax highlight for **page**-files but not for **apex**:

![eclipse-mars-dark](https://cloud.githubusercontent.com/assets/3514015/15799541/e6bead3c-2a68-11e6-9d14-ae313c6f2b41.png)

**Comment by vazexqi** [comment]
Acknowledged.

Just FYI @guw — this was what we discussed the other day.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
