### ISSUE TITLE
Unit Test Results not displaying

### ISSUE THREAD

**Issue by stuartajames** [forcedotcom/idecore#180]
Hello, I am attempting to run all the unit tests from the Force.com eclipse IDE plugin and when I do I get the following error

![image](https://cloud.githubusercontent.com/assets/5689119/15844813/ccd09300-2cb0-11e6-8105-d97a84f33fa3.png)

The code coverage results return, but not the test results.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
