### ISSUE TITLE
Force.com IDE Deployments with lightning components

### ISSUE THREAD

**Issue by stuartajames** [forcedotcom/idecore#181]
Hello, 

To get the lightning components to appear in my Force.com IDE I needed to include the following code block as the metadata GUI tool did not have it. 

```
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
```

This worked fine and the files are pulled in, but when we attempt to Deploy the code changes to another sandbox, we get an synchronisation error

![image](https://cloud.githubusercontent.com/assets/5689119/15844881/51c2c920-2cb1-11e6-9a59-b417001cae99.png)

And it won't let us deploy the lightning components to the specified server.

**Comment by vazexqi** [comment]
The current version of the IDE that you can install following the [instructions](https://developer.salesforce.com/page/Force.com_IDE_Installation) does *not* support Lightning. You can edit the package.xml as you did to try to retrieve/deploy but you will run into issues with syncing.

The next version will. I'm actually giving a presentation on that on the [TrailheaDX](https://developer.salesforce.com/trailheadx/agenda) (search for Lightning Developer Experience) if you want to get a preview.

**Comment by stuartajames** [comment]
Could you please link this ticket with the ticket for the so I can watch progress on this feature update
