### ISSUE TITLE
SObject names inconsistently highlit

### ISSUE THREAD

**Issue by cropredy** [forcedotcom/idecore#183]
IDE V36.0 Eclipse Mars.2

When I open a project, none of the SObject names are syntax highlit in blue within an Apex class.

Then, when I open the schema file for the org, and then go back to the classes and re-open them, some of the classes have the SObject name highlit and some do not.  Even for the exact same SObject name such as `ContentLicense__c`. With exact capitalization match. Classes are V36.0

Here's an example

From classA:
![With highlighting](http://i.imgur.com/XMQDrP7.png)

From classB:
![Without highlighting](http://i.imgur.com/yvEM8q3.png)

Baffled.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
