### ISSUE TITLE
Release date for v37.0??

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#184]
G'day @vazexqi and @gwestersfdc 

Was just curious if you have a release date for the v37 build that you can give us?  

Thanks for the help.

Cheers!

**Comment by anterokarttunen** [comment]
+1 would be cool. Last release v35 was long time ago 21 Oct 2015.

Currently "stuck" on using v35

**Comment by DouglasCAyers** [comment]
Using this update URL in the `Help | Install new software` menu gets you to version 36: http://media.developerforce.com/force-ide/eclipse45

Not quite 37, but close.

**Comment by guenthmn** [comment]
+1 I thought I heard end of August at the trailhead developer conference back in June

**Comment by chowwinston** [comment]
We are still fixing some bugs and it's unlikely we'll make it by the end of August. 

Is there anything preventing you from using the v37 beta? That has most of the features we are adding and it's stable.

**Comment by SergioHBG** [comment]
I believe this issue can be closed now: we are on v38 now...
