### ISSUE TITLE
Question: Is TypeInfo and MethodInfo available for all built-in classes?

### ISSUE THREAD

**Issue by jeffhube** [forcedotcom/idecore#185]
For some tooling I'm working on, I need to run ApexCompiler at least through the validate stage to resolve the types of Expression nodes. As far as I can tell, this means I need supply TypeInfo and MethodInfo for all of Salesforce's built-in classes.

Is that information available anywhere? I did see apex.jorje.semantic.symbol.type.InternalTypeInfos as well as the classes in apex.jorje.semantic.bcl, but those are rather incomplete. I'd like to avoid building all that info by hand, if possible.

Thanks,
Jeff

**Comment by vazexqi** [comment]
@jeffhube Unfortunately, we don't have those yet. To get a complete picture of all types, we need to combine several things including, but not limited to, user classes, Salesforce built-in classes for Apex, Salesforce built-in SObjects, user-defined Custom Objects, and some remaining "special" types like Flow.

There is a public description of the Salesforce built-in classes at https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/intro_rest_resources.htm (see /completions?type=apex) but you would need to write the translation yourself, for now.

Could you provide more details on the tooling that you are working on?

**Comment by jeffhube** [comment]
@vazexqi Thanks for the quick response. The tooling is nothing fancy - for starters I was just hoping to be able to identify all references to particular symbols, including sobject fields (in queries, initializers, etc.), which didn't look possible through just the tooling api.

Thank you for the tip on using the completions from the tooling api. I'll give that a try after I finish mapping sobject describe to typeinfo.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
