### ISSUE TITLE
Plugin Development Help

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#186]
I realize this is a Java newbie question however I have spent a considerable amount of time before positing here, hopefully it's something easy for someone more experienced and quick to answer.

I am trying to add a preference option to skip `checkForDirtyResource(...)` if the preference is activated, however I am unable to import 'ForceIdeEditgorPlugin` to get the value of the preference, if I use the CTRL+1 fix option to export the package it then results in a build path problem - any suggesions how to to fix this import or just read in my boolean preference `"saveToSarverCheckForDirtyDisabled"` ?

![import error](https://cloud.githubusercontent.com/assets/273413/16567576/50aff948-41ee-11e6-9cbd-945ed443d1e3.png)
![import error](https://cloud.githubusercontent.com/assets/273413/16567613/b9765e68-41ee-11e6-88e9-f4738b2c3e77.png)

```
Description	Resource	Path	Location	Type
A cycle was detected in the build path of project 'com.salesforce.ide.deployment.test'. The cycle consists of projects {com.salesforce.ide.ui, com.salesforce.ide.ui.editors, com.salesforce.ide.deployment, com.salesforce.ide.deployment.test, com.salesforce.ide.schemabrowser, com.salesforce.ide.test, com.salesforce.ide.upgrade, com.salesforce.ide.ui.editors.test, com.salesforce.ide.ui.test, com.salesforce.ide.upgrade.test}	com.salesforce.ide.deployment.test		Build path	Build Path Problem
```

**Comment by vazexqi** [comment]
@danielsokolowski 

The com.salesforce.ide.ui.editors plug-in already depends on com.salesforce.ide.ui plug-in. SaveToServerActionController is in the com.salesforce.ide.ui so you can't add a dependency to the ForceIdeEditorsPlugin, which is in com.salesforce.ide.ui.editors.

If you want to add a preference that only affects SaveToServerActionController, you can add it the com.salesforce.ide.ui plug-in or the com.salesforce.ide.core plug-in. See the prefererences section in https://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.core/src/com/salesforce/ide/core/ForceIdeCorePlugin.java#L270 for one example of how it is used.

**Comment by danielsokolowski** [comment]
Glorious, thank you for the help - https://github.com/forcedotcom/idecore/pull/190, please feel free to close this as needed.
