### ISSUE TITLE
"Force.com" -> "Show In Salesforce Web" option not working from file editor window

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#188]
The "Force.com" -> "Show In Salesforce Web" option is not working when I click on the option from the context menu available directly in the file editor window.

The "Force.com" -> "Show In Salesforce Web" option is working when I click on the option from the context menu available in the Package Explorer view.

My setup is:
- Force.com IDE plugin version: beta 37.0.0.201605121617
- Eclipse build "Eclipse Java EE IDE for Web Developers.", Version: Mars.2 Release (4.5.2), Build id: 20160218-0600

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
