### ISSUE TITLE
Question: Any chance to get an updated v37-beta?

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#189]
@vazexqi and @gwestersfdc 

The current v37 beta is just over two months old.  I know that you mentioned at TrailheaDX that the v37 plugin would be released in August.  I am just curious if we could get an updated v37-beta plugin to work with for the next 3-6 weeks.  You could leave the current v37-beta in place so we have something to revert back to if needed.  And, as always is the case with a beta, it comes "as-is".

You guys up for that?

Cheers!

**Comment by vazexqi** [comment]
I'm working on releasing the v37 beta by next week. It will have Lightning support in it. There will be some use cases that are not supported yet in that beta but I would like to get early feedback from the community. It will require Java 8 and Mars though. Stay tuned.

**Comment by ImJohnMDaniel** [comment]
@vazexqi EXCELLENT!!!  Much appreciated!

**Comment by vazexqi** [comment]
@ImJohnMDaniel 

https://git.soma.salesforce.com/DevTools/ide.core/wiki/Changes-in-Force.com-IDE-Beta-Version-37.0.0.20160720 **Note the update site URL change – you really need Mars to be using this**

https://git.soma.salesforce.com/DevTools/ide.core/wiki/Downloading-the-Beta-Version-of-the-Force.com-IDE

Please try it out and provide feedback. It's BETA and Lightning support is one of our biggest features to date so we really appreciate your feedback.

**Comment by ImJohnMDaniel** [comment]
Will do.  Cheers!

**Comment by ImJohnMDaniel** [comment]
@vazexqi QQ.   Since there is a new Eclipse Update URL, do we need to uninstall the older beta version of Force.com IDE first??

**Comment by vazexqi** [comment]
That's a good question. I don't think you need to since the version identifiers should still be the same regardless of update site URL. It should know that it's doing an upgrade.

**Comment by ImJohnMDaniel** [comment]
Ok.  Will give it a try.  Cross your fingers!!!  ;-)

**Comment by ImJohnMDaniel** [comment]
Well it did install.  Seeing something and will open a new case in a minute.
