### ISSUE TITLE
Monitor only SF files in `/src/` folder

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#19]
The Force IDE plug in zealously monitors all files in the project, so changes to files outside of `/src/` folder trigger the Force IDE builders.

For example renaming usually throws an error, deletion is tricky because you have to chose the preview mode and unselect 'Delete...' option, and the constant builder activation slows down of development (I have Force IDE builders disabled mainly for this reason).

![image](https://cloud.githubusercontent.com/assets/273413/3534560/6bcf538c-07ed-11e4-9dca-8b8cbe44a97d.png)

**Comment by chowwinston** [comment]
Thanks @KeithClarke !

**Comment by ImJohnMDaniel** [comment]
@vazexqi @chowwinston 

I see that these changes were merged on June 8th.  Were they included into the latest Beta release though?? (v37.0.0.201607202302)

If these changes were merged, then I would ask that we either reopen this issue or open a new one.  I am working on files outside of the /src/ folder and the plugin is trying to save to the server.

**Comment by ImJohnMDaniel** [comment]
PIng @vazexqi
