### ISSUE TITLE
Error on opening Eclipse - "Resource '/foobar' is not open" message shown

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#192]
I am getting the following error message when I open Eclipse

"Resource '/XXXXX' is not open"

![image](https://cloud.githubusercontent.com/assets/1149727/17066170/c90b4a54-5013-11e6-9a87-b6e0184a54a1.png)

There is an entry for every project in my workspace where the project is currently closed.

Stack trace in the Eclipse log file is attached.
[201607221355-log.txt](https://github.com/forcedotcom/idecore/files/378788/201607221355-log.txt)

I am running the following configuration:
- Eclipse: Mars.2 Release (4.5.2) - build id 20160218-0600
- Force.com IDE - v37.0.0201607202302  (including Debugger option)
- MEGA Lightning - v2.0.0.201607202302
- java version "1.7.0_75"

**Comment by vazexqi** [comment]
OK. I can repro locally. We are scanning all projects for lightning nature. We need to stop it for non-opened projects.

1. One thing I noticed is that you say that you're using java 1.7. I'm surprised that you can even load the plug-ins without Java 8. Java 8 is the minimal version.
1. Can you confirm if you dismiss the messages that you can still get Lightning on newly created project like auto-completion and outline view?

By the way, if you want to get Lightning features on current projects, you can right-click > Configure > Add Lightning support.

**Comment by ImJohnMDaniel** [comment]
@vazexqi - my apologies.  I am running Java 1.8.0_31.  I forgot that I configured Eclipse to run that using that jvm.

Just setup a new project and Lightning is enabled on the project.  I can see the mega.lightning.lightningNature nature in the project file.  The bundle editor opened the file correctly.

**Comment by ImJohnMDaniel** [comment]
@vazexqi Is there any chance that we could get a fix to this issue and a new beta build?

As a workaround, I have moved the alert box off to the side.  That allows me to continue working but performance degrades quickly and after a while, I need to restart Eclipse to get things working again.  While the issue is not a showstopper, it does hamper the evaluation of the beta build overall.

**Comment by ImJohnMDaniel** [comment]
@vazexqi - This scanning of all projects for lightning nature appears to be occurring very often.  Quite possibly for every file save; regardless if that file is a lightning JS file or not.

If that is true, why would you want to do that?

I would expect that you scan on the following events:
- Scan all open projects when Eclipse starts
- Scan/update the local project index as edits are done to that currently active project
- Scan project as it is opened in Eclipse.

Please correct me if I am missing something here, but what other times would you need to scan for lightning nature?

**Comment by vazexqi** [comment]
Taking a look today. I'll push out a new beta as soon as I identify the main issue behind this.

Also, are you working in online or offline mode? I'm guessing it's online mode and you can't switch back to offline because that dialog is blocking changes to the offline/online nature?

**Comment by ImJohnMDaniel** [comment]
@vazexqi - Yes, I am working in offline mode where possible.  I am able to move the dialog window out of the way and do things like switch between offline/online nature.

**Comment by vazexqi** [comment]
@ImJohnMDaniel I've pushed a new beta version that fixes this issue. Could you give it a try?

**Comment by ImJohnMDaniel** [comment]
@vazexqi Just installed the new version.
- this issue is resolved
- still have multi-tab editor
- still have auto-suggestion

I appreciate the quick turn around on this!!
