### ISSUE TITLE
"INVALID_CROSS_REFERENCE_KEY: No package named "Milestones PM+" while fetching metadata in Eclipse.

### ISSUE THREAD

**Issue by jmbauer** [forcedotcom/idecore#193]
When connecting the org to a project it gives the error above. The error also occurs when doing a refresh from server

**Comment by vazexqi** [comment]
@jmbauer Could you provide more context on this? I don't think Milestones PM+ is something that's built-in to the Force.com IDE.

**Comment by jmbauer** [comment]
Hi Nick,

Milestones PM+ is a managed package that is installed in the org. Why would
a managed package cause problems in the force.com IDE?

Going to Dreamforce 2016? Use promo code *EC16PALC* to get $100 off your
Dreamforce registration fee, compliments of Passage Technology.

Regards,
Joseph Bauer
Passage Technology
www.passagetech.com
Direct: 1-224-552-0081
Twitter:  @passagetech

**Comment by vazexqi** [comment]
@chowwinston Could you take a look at this? Milestones PM+ seems to be a freely installable package https://appexchange.salesforce.com/listingDetail?listingId=a0N30000009uYYMEA2

This might be similar to the issue we saw earlier with a particular package not respecting the foldering structure.

**Comment by chowwinston** [comment]
Digging into this now. Milestones is worse because you can't even pull the project. The other one #165 at least you can retrieve, just that the foldering is messed up.

**Comment by chowwinston** [comment]
The IDE retrieves installed packages as well. This is happening because we aren't encoding the name of the managed packages so the "+" causes it to not be found.

**Comment by jmbauer** [comment]
I can change the managed package to work around this. What would I need to
change exactly? I know I need to remove the + sign but where would I change
that?

Passage Technology is headed to Dreamforce! Click here
<http://www.passagetechnology.com/dreamforce-index#dreamforce-sessions> to
register for a session or simply stop by booth 114 during October 4-7th.
Not registered yet? Head over here
<https://www.salesforce.com/dreamforce/DF16/registration/?d=7010M000002IGbf> to
sign up and enter promo code *EC16PALC* to get $100 off your Dreamforce
registration fees.

Regards,
Joseph Bauer
Passage Technology
www.passagetech.com
Direct: 1-224-552-0081
Twitter:  @passagetech

**Comment by jmbauer** [comment]
I tried changing the app label on the .app file:

from <label>Milestones PM+</label>

to <label>Milestones PM Plus</label>

and that did not resolve the issue.


Passage Technology is headed to Dreamforce! Click here
<http://www.passagetechnology.com/dreamforce-index#dreamforce-sessions> to
register for a session or simply stop by booth 114 during October 4-7th.
Not registered yet? Head over here
<https://www.salesforce.com/dreamforce/DF16/registration/?d=7010M000002IGbf> to
sign up and enter promo code *EC16PALC* to get $100 off your Dreamforce
registration fees.

Regards,
Joseph Bauer
Passage Technology
www.passagetech.com
Direct: 1-224-552-0081
Twitter:  @passagetech

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
