### ISSUE TITLE
"Force.com Lightning Support" is not available when installing beta version

### ISSUE THREAD

**Issue by raJSN** [forcedotcom/idecore#194]
Hello Guys,

I am able to follow all the steps mentioned above. However, I don't see ""Force.com Lightning Support" option.

Can you guys help.

Thanks
Raj

**Comment by vazexqi** [comment]
@raJSN - What steps were you following? Sorry, the "all the steps mentioned above" loses it context when there's nothing above ;-)

**Comment by raJSN** [comment]
Ohh.... I missed context here :P.

So, I was installing beta version of Force.com Ide which is available with Lighting support (Thanks to you guys). In the [wiki](https://github.com/forcedotcom/idecore/wiki/Downloading-the-Beta-Version-of-the-Force.com-IDE) there was step that says check "Force.com Lightning Support", however i didn't got this option while installing.

I guess this option is renamed to "MEGA Lightning".

Thanks
Raj
