### ISSUE TITLE
Regression issue - Monitor only SF files in `/src/` folder

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#197]
@vazexqi, I am raising this as a regression bug from #19 

The Force IDE plug is still monitoring all files in the project and not simply the /src/ folder.

Steps to reproduce:
1) Have Force.com project that is online
2) Create a text file called blue.txt on the project root folder
3) ...the plugin tries to build the workspace.

I am running the following configuration:

Eclipse: Mars.2 Release (4.5.2) - build id 20160218-0600
Force.com IDE - v37.0.0.201607262223 (including Debugger option)
MEGA Lightning - v2.0.0.201607262223
Java version "1.8.0_31"

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
