### ISSUE TITLE
No way to create or sync Lightning Events for anap

### ISSUE THREAD

**Issue by deepeshchourey** [forcedotcom/idecore#198]
There seems to be no way to create an event, that could be registered for components via IDE. During the sync process from the Dev Org, events created using Developer Console is also not showing up in the IDE.

Please let me know if I am missing something here.

**Comment by vazexqi** [comment]
@deepeshchourey Can you fill out the following bug template?

### Summary
_Short summary of what is going on or to provide context_.

### Steps To Reproduce:
1. This is step 1.
1. This is step 2. All steps should start with '1.'

### Expected result
_Describe what should have happened_.

### Actual result
_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**Force.com IDE version**:

**OS and version**:

**Java version**:


If you can't copy-paste that, you can get the raw template from https://github.com/forcedotcom/idecore/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by deepeshchourey** [comment]
My mistake. I found the way to deal with events in the Beta version. Thanks.
