### ISSUE TITLE
Getting installation error when updating to latest Beta v37.0.0.201609142037

### ISSUE THREAD

**Issue by vc4u** [forcedotcom/idecore#201]
### Summary
I'm trying to update the Force.com IDE plugin to following available verison:
  Force.com IDE	 - 37.0.0.201609142037

When I try to update it to latest available beta version I'm getting following error which I've no idea on how to resolve.

```
Cannot complete the install because one or more required items could not be found.
Software currently installed: SVNKit Client Adapter (Not required) 1.8.9 (org.tigris.subversion.clientadapter.svnkit.feature.feature.group 1.8.9)
Missing requirement: SVNKit pure Java Subversion Library 1.8.12.r10533_v20160129_0158 (org.tmatesoft.svnkit 1.8.12.r10533_v20160129_0158) requires 'bundle com.trilead.ssh2 [1.0.0,2.0.0)' but it could not be found
Cannot satisfy dependency:
From: SVNKit Client Adapter (Not required) 1.8.9 (org.tigris.subversion.clientadapter.svnkit.feature.feature.group 1.8.9)
To: org.tmatesoft.svnkit [1.8.0,1.9.0)
```
Can anyone suggest me how to fix this error?

**Force.com IDE version**:
Force.com IDE (Beta)	37.0.0.201607262223

**OS and version**:
Windows 10 (64-bit)

**Java version**:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by vazexqi** [comment]
@vc4u Which instance of Eclipse are you using (j2ee, Java, rcp)? 

And do you have SVN plug-ins installed in that instance?

What happens when you try to install in a fresh instance of Eclipse j2ee from http://www.eclipse.org/downloads/packages/release/Mars/2

**Comment by vazexqi** [comment]
Just FYI, I just tried it on a fresh instance of Eclipse Mars J2EE and I didn't get any installation errors. So, it might be related to your current Eclipse installation. If you can share the list of plug-ins you have installed, I might be able to help more.

**Comment by vc4u** [comment]
Thanks @vazexqi sorry for not replying earlier. I was able to get past the error by first updating SVNKit from here - http://eclipse.svnkit.com/1.8.x/

and then I was able to install the Beta plugin. I've attached my eclipse installation details.

![2016-09-27_1700 1](https://cloud.githubusercontent.com/assets/8048832/18871673/1e3b5ce0-84d4-11e6-8469-4d9218218428.png)

**Comment by vazexqi** [comment]
@vc4u - This seems to be specific to the SVNKit library and there doesn't appear to be anything that we can do on our end forcing its update. What you did was probably correct, i.e., updating it first before updating the IDE.
