### ISSUE TITLE
Deploy a Flexipage (lightning page) to another org

### ISSUE THREAD

**Issue by jmbauer** [forcedotcom/idecore#202]
### Summary

_Short summary of what is going on or to provide context_.
Edit a page layout in lightning experience (a flexipage) and when refreshing that into the eclipse ide it works fine. But when I deploy that to another org I get this error:

component access denied to component forceChatter:recordFeedContainer
### Steps To Reproduce:
1. This is step 1. Create a flexipage in the UI in Lightning and then refresh from server in eclipse
2. This is step 2. All steps should start with '1.' deploy the flexipage to another org
### Expected result

_Describe what should have happened_.
it should create the page in the other org
### Actual result

_Describe what actually happened instead_.
Error: component access denied to component forceChatter:recordFeedContainer
### Additional information

_Feel free to attach a screenshot_.

**Force.com IDE version**:
36.0.0.201601221512
**OS and version**:
OS X 10.11.1
**Java version**:
Java 8 build 1.8.0_73-b02

**Comment by spring-work** [comment]
Any resolution to this? We are facing the same issue deploying flexipage

**Comment by sfdev2018** [comment]
I faced similar issue. This is caused when the chatter is disabled. I activated the chatter by going to Setup -> Customize -> Chatter -> Chatter Settings

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
