### ISSUE TITLE
Force.com IDE v37.0 does not refresh standard objects metadata from server

### ISSUE THREAD

**Issue by franmico** [forcedotcom/idecore#203]
### Summary

When I refresh from server standard objects the metadata does not get updated. I have double check my package.xml metadata and everything is correct. With the older veersion it was working.
### Steps To Reproduce:

Select in the package explorer a standard object then right click, Force.com > Refresh from Server
### Expected result

The metadata of the standard object that has been refreshed from server does not get updated with the new fields I've created in my dev org. It works fine for custom objects.
### Actual result

The refresh from server process starts but nothing gets updated in the local file that contains the metadata.
### Additional information

**Eclipse version**: Neon Release (4.6.0)

**Force.com IDE version**:  Froce.com IDE (37.0.0.201609220436)

**OS and version**: Windows, Windows Server 2012 R2

**Java version**: Java 8 (8.0.1020.14)

**Comment by ThomasCreemers** [comment]
I have the same issue. Is there a workaround for this ? If I refresh the object folder only the Custom Objects are refreshed. Standard Objects are skipped. 

When refreshing the standard object's specific file also nothing happens.

**Comment by vazexqi** [comment]
@chowwinston - Could you take a look at this? I thought this was fixed in https://github.com/forcedotcom/idecore/commit/4b047d9e64251079876fdb413be92f848263a79e

I'll pull it into our backlog for next week.

**Comment by ThomasCreemers** [comment]
Is there any update on this defect ?

**Comment by chowwinston** [comment]
Hi @ThomasCreemers sorry I haven't had a chance to work on this yet. I'll take a look this week.

**Comment by chowwinston** [comment]
We'll have a fix out for this some time soon. The commit @vazexqi mentioned fixed a more critical bug but broke this one in the process.

In the meantime, you'll have to delete the file locally and refresh the top-level src folder to pull the standard object back. 

Sorry for the inconvenience.

**Comment by franmico** [comment]
Thanks for the update :)

**Comment by ThomasCreemers** [comment]
Any Update on this one :). Sorry for pushing this but we have a big project running with 20+ developers who where forced to update from API 35 to API 37 for Continuous Integration reasons. However this bug is putting some stress on the project.

**Comment by vazexqi** [comment]
This is fixed in the latest beta https://github.com/forcedotcom/idecore/wiki/Downloading-the-Beta-Version-of-the-Force.com-IDE
