### ISSUE TITLE
Force.com errors showing on Generic Eclipse project

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#204]
### Summary

I am seeing errors on Apex files even though the Eclipse project is generic in nature
### Steps To Reproduce:
1. Setup generic Eclipse project.... "bluemarlin"
2. Add "/src" directory.   Add "/src/classes" directory
3. Add new file of "/src/classes/foobar.cls"

Error message shows of "unexpected EOF"
### Expected result

No error message should be shown.  This is a generic Eclipse project
### Actual result

The class file is being parsed and errors are being reported.
### Additional information

**Force.com IDE version**:
v37.0.0.201609220436

**Eclipse version**:
Eclipse Java EE IDE for Web Developers.
Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200

**OS and version**:
MacOS Sierra v10.12

**Java version**:
1.8.0_31

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
