### ISSUE TITLE
Could we update the 'Contributing-Code' wiki page to include direct link to https://github.com/forcedotcom/idecore/wiki/FAQ#contributing

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#205]
### Summary
The 'https://github.com/forcedotcom/idecore/wiki/FAQ#contributing' is very helpful but not directly accessible through the `Readme.md`. The readme me links to 'Contributing-Code' so could we update that page to link to the full guide here 'https://github.com/forcedotcom/idecore/wiki/Getting-Started'

Sorry I can't do a pull request for a wiki: http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by vazexqi** [comment]
The https://github.com/forcedotcom/idecore/wiki/Contributing-Code has been updated to include a link to the Getting Started page.
