### ISSUE TITLE
Unable to create 'aura' components

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#207]
### Summary
Unable to create aura components, must create the component in developer console then push from Eclipse as a work around. 

### Steps To Reproduce:
1. Manually crate a basic aura component locally
1. Right click and push to server.

### Expected result
Creation of the component. 

### Actual result
Error UNKNOWN_EXCEPTION (UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1202083855-25892 (306928315))

### Additional information
![image](https://cloud.githubusercontent.com/assets/273413/20225375/fff4754a-a810-11e6-8bd8-1fd0f46a6196.png)

**Force.com IDE version**:
38.0

**OS and version**:
Windows 10

**Java version**:
1.8

**Comment by vazexqi** [comment]
@danielsokolowski Got it. Thanks for including the error number. Checking with 306928315 shows that there might be some issues with deployment of AuraBundles using Metadata API. Routing to the team internally to take a look now.

Will also check if we have issues on the IDE side.

By the way, how are you using Version 38.0 of the IDE? Are you building your own version from the source?

**Comment by vazexqi** [comment]
@danielsokolowski I am using my local **v38.0** of the IDE. I tried your repro steps with a new basic Lightning Component and can't reproduce. 

Can you provide more details? I can see from our server logs that we do see that error but I don't have a repro step.

**Comment by vazexqi** [comment]
Our Lightning team analyzed the error and seem to have determined that it was because of an empty markup body. Could you verify if that is the case, i.e., was your Lightning component's markup empty?

**Comment by danielsokolowski** [comment]
Hello @vazexqi I do believe so as I was copying an existing component over, renaming it, then attempting to 'Save to server'. 

However I've done tests and results imply there has been some changes:

Manually creating a component by creating a folder, an **empty**  `.cmp` and standard `.cmp-meta.xml` results in ' WARN [2016-11-21 10:11:17,567] (PackageDeployService.java:deployWork:326) - Unable to retrieve components: ServiceException: UNKNOWN_EXCEPTION (null: Required fields are missing: [Source])

Same as above but with `<aura:component access="global"></aura:component>` in the `.cmp` body works.

Simply coping and pasting another auro folder (component), ex Testing > Testing2 works, it creates the component in SF and automatically renames the supporting component files:

![image](https://cloud.githubusercontent.com/assets/273413/20488152/066e2658-afd4-11e6-901c-daaaf6abbdbc.png)

**Comment by vazexqi** [comment]
So, yes, you **can't** have an empty MARKUP for any Lightning bundle, where a bundle is an app, component, event, etc.

1) Can you paste the contents of what were the basics of what you are trying to save? The contents when you first filed this bug, I mean.

2) Also, can you use the wizards to create the Lightning bundles in the future? File > New > Lightning Bundles will help you get started. I am curious if this is because you might have missed something when you were creating the files manually.

**Comment by vazexqi** [comment]
@danielsokolowski Any updates to my questions previously?

**Comment by danielsokolowski** [comment]
Hi @vazexqi sorry looks like I missed your message. 

1. I can't assist with number 1, it was a project ago and I don't recall the details. I promise to paste code in the future and/or if I run into this issue again.

2. I very likely did miss something as I was not aware of the File > New > Lightning Bundles. 

Please feel free to close this and sincerely thank you for evolving the IDE.
