### ISSUE TITLE
IDE test runner runs all test in Org after choosing all tests in Project

### ISSUE THREAD

**Issue by latentfuss** [forcedotcom/idecore#208]
### Summary
_I'm trying to run the two test Classes in a single project, but the test runner kicks off ALL the tests in the Org_.

### Steps To Reproduce:
1. Create a project with two test Classes
1. Create a run configuration. Choose current Project, and `(all Classes)`
1. Apply changes and run
1. All test Classes in Org begin running

### Expected result
_The test runner should have only run the test Classes in the current Project_.

### Actual result
_All test Classes in Org begin running_.

### Additional information

_![available classes](https://cloud.githubusercontent.com/assets/3143753/20282658/b1d2feac-aa83-11e6-9650-17a0dba030d1.png)_.

**  Force.com IDE	37.0.0.201609220436	com.salesforce.ide.feature.feature.group	salesforce.com**:

**Win 7 Professional 64 bit, Service Pack 1**:

**Java version 8 Update 25  (build 1.8.0_25-b18)**:

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
