### ISSUE TITLE
Full Metadata Retrieval on Static Resource save

### ISSUE THREAD

**Issue by triestelaporte** [forcedotcom/idecore#210]
In previous versions of the IDE I could make changes to javascript stored in static resources and save like any other component.  After updating to v37 it looks like a complete, and slow, re-retrieve takes place after every save.  

### Steps To Reproduce:
1.  Create new Project
1.  During Project Creation Subscribe to a Package (Not sure if this matters, but it's how I am set up)
1.  Make sure package contains at least one static resource containing only plain text javascript
1.  Set project to Work Online, and set Eclipse to Build Automatically
1.  Open resource, make any change, hit Ctrl-S
1.  Observe IDE build workspace and then retrieve all metadata components.  This particular project has 1800 and this takes a few minutes each time.

### Expected result
I would expect the save to happen like I remember it used to work, and like it happens on classes and VF.  The save completes quickly and the rest of the metadata is not retrieved.

### Actual result
IDE spends a few minutes retrieving all contents of the package on save.

### Additional information

**Force.com IDE version**: v37

**OS and version**: Windows 10

**Java version**: 1.8

** Eclipse Version:  neon

**Comment by triestelaporte** [comment]
This same thing happens when saving any piece of an aura bundle in v38.  This makes any sort of lightning development through Eclipse incredibly slow.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
