### ISSUE TITLE
Question: Why does the IDE periodically hang at "Invoking 'Force.com online builder'" step

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#211]
### Summary
Periodically, I will save an Apex file and the IDE will get stuck at the "Invoking 'Force.com online builder'" step.  The IDE is completely unusable at this point and I have to wait until this completes.  I have not found a repeatable pattern of when a save of an Apex file is affected by this issue but it does happen several times a day.  I could be coding, saving multiple times for the same Apex class or other classes and then randomly a save is completely paused in this step.

@vazexqi : Any thoughts as to why this would occur?  Is there a way to determine if this is an IDE issue or a ToolingAPI issue?

Obviously, with these delays, it can make it very difficult to get things done.

### Steps To Reproduce:
1. Occurs frequently through the day but no discernible pattern to reproduce

### Expected result
Save process would complete in under 10 seconds.

### Actual result
Save process hangs for 5-10 minutes before completing

### Additional information

**Force.com IDE version**:
37.0.0.201609220436

**Eclipse Version**
Neon 1.a Release 4.6.1

**OS and version**:
MACOS Sierra v10.12.1

**Java version**:
jdk1.8.0_31

**Comment by ImJohnMDaniel** [comment]
Hey @vazexqi - Just an FYI, I am seeing the same behavior on Force.com IDE version 38.0.0.201612141658 from the Beta update site.

**Comment by AndyRouse42** [comment]
I'm not sure if this is the issue you're seeing, but I find the IDE will hang in scenarios where a compilation issue has popped up (a dependant class no longer exists, etc.). I will have to go to the Developer section within the Admin User Interface to untangle the issue and then refresh the IDE code. It seems that the tooling API doesn't handle this scenario well, as the same issue occurs in the Developer Console.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
