### ISSUE TITLE
Refreshing Metadata Components unchecks Standard Objects

### ISSUE THREAD

**Issue by mintotsai** [forcedotcom/idecore#213]
### Summary
When adding/removing the projects metadata components, the standard objects checkbox is unchecked.

### Steps To Reproduce:
1. Right click on project
1. Go to Force.com menu
1. Click Add/Remove Metadata Components...
1. Click Add/Remove... button

### Expected result
The originally selected standard objects and fields should be preserved.

### Actual result
All standard objects and fields are unchecked.

### Additional information

![choose_metadata_components_and_properties_for_jasmine_and_jasmine_force_-_force_com_-_jasmine_src_objects_contact_object_-_eclipse_and_new_issue_ _forcedotcom_idecore](https://cloud.githubusercontent.com/assets/1557318/22113307/6f20958e-de2b-11e6-875c-2a038b938b6b.png)

**Force.com IDE version**:

38.0.0.201701101558

**OS and version**:

macOS Sierra 10.12.2

**Java version**:

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
