### ISSUE TITLE
Single file synchronize with server doesn't recognize remote file.

### ISSUE THREAD

**Issue by mintotsai** [forcedotcom/idecore#214]
### Summary
When synchronize with server on a single file, the ide thinks that the remote file is empty. The workaround is to synchronize a whole directory

### Steps To Reproduce:
1. Open a file
1. Right click on file
1. Got to Force.com
1. Synchronize with Server

### Expected result
Expect the ide to recognize the remote file and show a diff.

### Actual result
The ide does not see the remote file.

### Additional information

![jasmine_force_-_force_com_-_synchronize_w_______workspace____jasmine_src_classes_calendarcontroller_cls_-_eclipse](https://cloud.githubusercontent.com/assets/1557318/22223154/70cabc96-e17f-11e6-9fa3-e9ff0e1dd6b3.png)

**Force.com IDE version**:

38.0.0.201701101558

**OS and version**:

macOS Sierra 10.12.2

**Java version**:

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
