### ISSUE TITLE
Update links on Getting Started page

### ISSUE THREAD

**Issue by salbertson** [forcedotcom/idecore#215]
### Summary
I was going through the steps on the Getting Started wiki page and noticed the [Eclipse Plug-ins 3rd Edition](http://www.qualityeclipse.com/) needs updating.

### Steps To Reproduce:
1. Go to [Getting Started](https://github.com/forcedotcom/idecore/wiki/Getting-Started)
2. Click on [Eclipse Plug-ins 3rd Edition](http://www.qualityeclipse.com/)

### Expected result
The link should take you to Amazon or somewhere the book can be found.

### Actual result
The link takes you to a placeholder page, not anything useful to find the book.

### Additional information
![screenshot 2017-01-25 10 08 29](https://cloud.githubusercontent.com/assets/154463/22303021/42864ab8-e2e6-11e6-96dd-07430ac9d263.png)

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
