### ISSUE TITLE
Return Method Parsing issue in Outline View

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#216]
### Summary
The outline view will incorrectly parse the return type of a method if that return type is qualified by a namespace.

### Steps To Reproduce:
1. Create foobar class
1. Add the following method
`public List<SObjectField> getFields() {  return null; }`
1. The outline view for this method correctly shows:
![image](https://cloud.githubusercontent.com/assets/1149727/22529894/3cc2a1a0-e8a7-11e6-8e96-90a3c2b57727.png)
1. Add the following method
`public List<Schema.SObjectField> getFields() {  return null; }`
1. The outline view for this method incorrectly shows:
![image](https://cloud.githubusercontent.com/assets/1149727/22529923/6990826a-e8a7-11e6-809c-2ef3d38db9b2.png)

**Force.com IDE version**: v38.0.0.201701101558

**OS and version**: macOS Sierra version 10.12.3

**Java version**: java version "1.8.0_121"

**Eclipse version**: Eclipse Java EE IDE for Web Developers. Version: Neon.2 Release (4.6.2) Build id: 20161208-0600

**Comment by lakshamanp** [comment]
haiiiiiiiiii

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
