### ISSUE TITLE
Project Content with Package cannot be deployed to server / package.xml empty -V37 & V38 

### ISSUE THREAD

**Issue by guenthmn** [forcedotcom/idecore#219]
### Summary
Projects created with content of a package will load correctly on Mac and Windows, but when you try to deploy the project to another instance the system will try to create all artifacts. I found that the package.xml file is empty. In version 36 the file looks like this:

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>Portal</fullName>
    <types>
        <members>AppSC</members>
        <members>DhaAnswerBlockCon</members>
       .......

in version 37 and 38 the fullName is missing/empty:

### Steps To Reproduce:
1. Create an unmanaged package on the server and add some metadata (apex class preferred) to it.
2. Create a new project in eclipse, for content switch to package and select the package created in step 1 as the source
3. Save package and refresh from server
4. Make change to an apex class and save to server
5. Select Project folders and select "Deploy to Server"
6. Authenticate to target server (production)
7. The system will display that all metadata as needing to be created (green) exiting metadata on the target server is not identified.

I found that the package content is not listed in the package.xml file for version 37 and 38.

36 works correctly
 

### Expected result
When deploying to target server the existing metadata should be updated (yellow) or skipped (grey)

### Actual result
Program tries to add existing data to target server and fails since it exists

### Additional information

Force.com IDE V 37 and 38

Both Windows 10 and Mac (10.12.3) Versions

**Comment by guenthmn** [comment]
This is a critical issue for us. Were you able to reproduce?

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
