### ISSUE TITLE
Feature: ctrl + click shorcut to jump code

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#22]
Most Eclipse language plugins I've used have this feature: doing `ctrl+click` on a method, function, etc. takes you to the place and even different file where the item is defined.

**Comment by andrew-chiz-muzychuk** [comment]
Need this.
+1

**Comment by RJPalombo** [comment]
Hi @vazexqi, has there been any movement on this?

**Comment by Patlatus** [comment]
There is Illuminated Cloud plugin for IntelliJ Idea which allows to use Ctrl-Click feature. Using it instead of Force.com IDE now

**Comment by gwestersfdc** [comment]
This feature is in development.
