### ISSUE TITLE
Aura is not showing up as a choice in 'Choose Initial Project Contents' or on Add/Remove Components

### ISSUE THREAD

**Issue by alo-sen** [forcedotcom/idecore#221]
Aura is not showing up as a choice in 'Choose Initial Project Contents' or on Add/Remove Components

### Steps To Reproduce:
When I create a new project I do not see the Aura component as a choice by default. When I come back on the project to Add/Remove components the Aura is still not available. 
This is an issue on my work desktop but this works on my home laptop. Any setting or update of Java that I should be aware of?
I do see a message 'Unable to get AuraDefinitionBundle'.

### Additional information

_Feel free to attach a screenshot_.
![image](https://cloud.githubusercontent.com/assets/20431589/25440643/a5bb885c-2a65-11e7-988a-e97fa4aceaba.png)

**Force.com IDE version**:
Neon.3 Release (4.6.3)
**OS and version**:
Windows 7 Enterprise
**Java version**:
Java Version 8 Update 121

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
