### ISSUE TITLE
Many components not supported

### ISSUE THREAD

**Issue by okram999** [forcedotcom/idecore#222]
### Summary
I get the below windows showing the list of components not supported in eclipse. I am trying to get the team use the force IDE plugin, but the list of components seem to have some the ones that we uses. 
I am not a salesforce developer, but I would like to know these:

1. Does this mean we should not use the Ecllipse IDE as it have components that we use and not supported?
2. If we still use the IDE, how do we get the package XML for retrieving and deploying, in this situations?

![capture](https://user-images.githubusercontent.com/10067711/27198396-9d5ac184-51d7-11e7-81e3-bc99e2ba4dfe.PNG)

### Steps To Reproduce:
Eclipse Java EE IDE for Web Developers.
Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500

![2](https://user-images.githubusercontent.com/10067711/27198456-dd6b6dd2-51d7-11e7-8bb5-b834ec4788fd.PNG)

1. connect to developer edition
2. Right click -> properties -> Force.com -> Add/Remove 

### Expected result
Should it support everything?

### Actual result
I am getting a windows showing a list of components not supported

### Additional information

**OS and version**:
Win7

**Java version**:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
