### ISSUE TITLE
Synchronizing individual lightning file pushes the entire component bundle

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#223]
### Summary
When in synchronize view, choosing say a `.css` file to be saved to server pushes the entire component as well. This is very bad behaviou because it will result files on the server being overwritten where when did not choose to do so; I have lost changes that I wanted to import from the server.

### Steps To Reproduce:
1. Have some local differences in a lighting component. 
1. Choose synchronize with server, and right click on one of the files and choose apply project to server, all other local files are also pushed. 

### Expected result
Sync only what I have selected to be synced. 

### Actual result
All local files are pushed to server. 

### Additional information

N/A

**Force.com IDE version**:
Force.com IDE version 39.0

**OS and version**:
Windows 10

**Java version**:
build 1.8.0_91-b15

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
