### ISSUE TITLE
Can't see logs in Apex Test Results

### ISSUE THREAD

**Issue by cunnike** [forcedotcom/idecore#224]
### Issue
Whenever I run a test I can't see any of the logs in the Apex Test Results view despite the fact that I selected the Use Logging checkbox in the Run configs. 

Here are my run cofigs:
![runconfigs](https://raw.githubusercontent.com/cunnike/images/master/logLevels.PNG)

Here is a test class I used to recreate the issue:
![testpane](https://raw.githubusercontent.com/cunnike/images/master/NewTestCode.PNG)

Here is the system debug logs after running my example test:
![debuglogs](https://raw.githubusercontent.com/cunnike/images/master/noDebug.PNG)
As shown above even though I selected the test method I can't see the system debug log.

Similarly I can't see the stack trace when the test fails:
![badCode](https://raw.githubusercontent.com/cunnike/images/master/badCode.PNG)
![noStack](https://raw.githubusercontent.com/cunnike/images/master/nostack.PNG)

I can however see the code coverage:
![yesCode](https://raw.githubusercontent.com/cunnike/images/master/yesCodecoverage.PNG)

Here is my package.xml for this project just to show that the api version is 38.0: 
[package.xml](https://github.com/cunnike/images/blob/master/package.xml)

**Force.com IDE version**: v38.0
**Eclipse version**:  Neon 3 Release (4.6.3)
**OS and version**:  Windows 7 Pro
**Java version**:  1.8.0_131

**Comment by ppinck-CardTapp** [comment]
I'm having the same problem. Did this ever resolve itself?

**Comment by psamsotha** [comment]
Same problem v38.0 Eclipse Photon

**Comment by bzavalaf** [comment]
I'm having same problem
Force.com IDE version: v38.0
Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500
OS and version: Window 10
Java version: 1.8.0_131

Error:
MESSAGE ERROR [2018-10-15 22:54:22,076] (RunTestsView.java:runTests:258) - Problem reading test result: {"successes":[{"namespace":null.....

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
