### ISSUE TITLE
Selection of individual `CustomLabels` not working

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#226]
### Summary
It appears only deploying/downloading all custom labels is supported even though the UI let's you pick individual ones. If one manually updates the `package.xml` to list only certain custom labels things seem to function as normal. 

![image](https://user-images.githubusercontent.com/273413/28172233-0b46bf08-67b9-11e7-9061-0a721e74c42c.png)

### Steps To Reproduce:
1. Select individual labels.
1. Review contents of `\src\labels\CustomLabels.labels` note it's all labels.

### Expected result
`package.xml` should be as follows, NOTE the lack of `s` in `CustomLabel`, it's a different metadata type name:
```
<types>
        <members>Foo Bar</members>
        <members>Foo Bar 2</members>
        <name>CustomLabel</name>
    </types>
```

### Actual result
`package.xml` is as follows: 
```
<types>
        <members>CustomLabels</members>
        <name>CustomLabels</name>
    </types>
```

### Additional information
A work around is to manually update and maintain  `package.xml` and be mindful not to select or use th e Force.com IDE UI for the `labels` metadata type. 

**Force.com IDE version**:
39.0

**OS and version**:
Windows 10

**Java version**: 1.8

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
