### ISSUE TITLE
"all methods" selection for test run configurations does not discover new methods

### ISSUE THREAD

**Issue by jgarbers** [forcedotcom/idecore#230]
### Summary
When setting up run configurations for tests, the _all methods_ choice for "Test method" appears to include only test methods defined *when the run configuration is defined*, rather than executing all test methods of the class at the time it's run.

### Steps To Reproduce:
1. Create a test class with a method "testOne".
2. Create a run configuration to run that class and choose _(all methods)_ for the "Test method".
3. Run the test and note that "testOne" has been executed.
4. Edit the test class and add method "testTwo".
5. Run the test case again.

### Expected result
Both testOne and testTwo methods were run.

### Actual result
Only testOne is run.

### Additional information
This behavior has caught me several times when adding new test cases. I add a test method and re-run the tests; the result is all "green" even though my new method might have failed, because the new method didn't get executed. Unless I remember to click the _Search_ button and "re-apply" the _(all methods)_ choice each time I add a test method, I'm likely to miss the fact that my new method didn't get run.

**Force.com IDE version**:
Mars.2 Release (4.5.2)

**OS and version**:
macOS Sierra Version 10.12.6

**Comment by DatGuyJonathan** [comment]
@jgarbers , which Force.com IDE version do you have? Are you able to reproduce this after saving the code change to server and verifying your org has the new test method?

**Comment by jgarbers** [comment]
IDE version is Mars.2 Release (4.5.2) as mentioned above -- if there's some other version info I can supply, just let me know where to find it. Not quite sure what you mean in your second question, but the workflow is: add a new test method to SomeControllerTests.cls and save the change. I see "Building workspace (0%)" down on the status line for a moment.  Once that goes away I click the "play" button to invoke the last run configuration, which was set up with "(all methods)" on SomeControllerTests.cls. The tests run, but the results do not include the new test method. I then open up the run configuration, click "Search" for the "Test method", choose "(all methods)", "Apply", and "Run". Then the results _do_ show the new test method. Does this help?

**Comment by DatGuyJonathan** [comment]
@jgarbers , click Help > About, then click Installation Details. In the list of Installed Software, there should be one called Force.com IDE. What is the version that you have?

**Comment by jgarbers** [comment]
That'd be 36.0.0.201601221512.  Assuming that latter bit is a date, it seemed a bit old, but clicking "Update" gave me "No updates were found."

**Comment by DatGuyJonathan** [comment]
@jgarbers We fixed the issue you described in version 37. Could you uninstall your version 36 and re-install from https://developer.salesforce.com/media/force-ide/eclipse45 ?

**Comment by jgarbers** [comment]
Got the new plugin (version 38) and the problem no longer appears. Sorry to report a bug on an old version, but I thought "Check for updates" would get me newer code. The site URL that I had configured was "Salesforce IDE - http://media.developerforce.com/force-ide/eclipse42" -- is there a way to know when a new one is needed? Thank you!

**Comment by DatGuyJonathan** [comment]
@jgarbers , this documentation explains the difference between those two URLs: https://developer.salesforce.com/docs/atlas.en-us.eclipse.meta/eclipse/ide_install.htm. Good to hear it worked out!
