### ISSUE TITLE
Question: Why does the IDE use the metadata api to save lightning bundle changes

### ISSUE THREAD

**Issue by StuartThomsonKimble** [forcedotcom/idecore#231]
### Summary
The metadata api is very slow to deploy changes and frequently my small changes get queued in salesforce for several minutes. You can see queued metadata requests in salesforce in the deploy status screen (/changemgmt/monitorDeployment.apexp). When saving changes using the tooling api (through the dev console) changes are saved much quicker.

### Steps To Reproduce:
1. Occurs frequently.

### Expected result
I would like to use the tooling api for saving changes to lightning bundles - even if it means changing each artifact (.cmp, .controller, .css) separately.

### Actual result
Saves are performed using the metadata api.

Eclipse IDE for Java Developers
Version: Oxygen Release (4.7.0)
Build id: 20170620-1800

Force.com IDE	38.0.0.201701101558	com.salesforce.ide.feature.feature.group	salesforce.com

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
