### ISSUE TITLE
QUESTION: Apex Jorje Parser & Virtual keyword in AST

### ISSUE THREAD

**Issue by JAertgeerts** [forcedotcom/idecore#232]
As we're adding rules to the [PMD](https://github.com/pmd/pmd/pull/625) ruleset we found ourselves in the situation where we needed to see if a method / class has the virtual keyword or not. We couldn't find it on any node in the AST, do you know if it's supported or how we could get access to it?

Tagging @vazexqi as he helped us on reverse engineering the jorje parser for PMD before.

**Comment by rsoesemann** [comment]
Did you load a class with virtual into the Rule Designer an inspect the properties of the AST? That was always helpful to me.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
