### ISSUE TITLE
Please provide Dependency list of Jorje Modules for PMD

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/idecore#233]
To make Apex work in the static code analyzer we use the byte code jars of Jorje.

As described in https://github.com/pmd/pmd/issues/605#issuecomment-337001249 we made PMD less dependent on an Uber Jar for all the Jorje modules we need.

Can you provide us a list of all the Jorje Dependancies. Maybe a maven or Ant file?

FYI: @vazexqi

**Comment by adangel** [comment]
Just for reference, these are the dependencies, we know of - but we don't know, whether the versions are correct:

groupId | artifactId | version
-----|----|----
com.google.guava|guava|22.0
org.antlr|antlr-runtime|3.5.2
org.ow2.asm|asm|6.0

**Comment by vazexqi** [comment]
@adangel - Sorry for the late response. Are you able to use the über jar from https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex/out  

It's basically the same jorje jar but with the language server protocol support on top of it.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
