### ISSUE TITLE
Packaged objects not showing in 'Choose Metadata Components'

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#234]
### Summary
Unable to select packaged objects in the 'Choose Metadata Components' so that one can edit custom additional fields.

### Steps To Reproduce:
1. Attempt to select any managed object you have access to add fields to, it will not show up in the UI

### Expected result
Ability to select the managed object and custom fields on it. 

### Actual result
Packaged object not visible or listed.

### Additional information

I am able to pull the actual metadata for the custom fields on the managed object by editing the `package.xml` direclty.

**Force.com IDE version**:
Force.com IDE version 39.0

**OS and version**:
Windows 10 64bit

**Java version**:
1.8.0_91

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
