### ISSUE TITLE
Jorje parses invalid code as valid

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/idecore#236]
### Summary
In PMD 6.0.0 we are using the Jorje parser 1.0-sfdc-224-SNAPSHOT. As part of this issue https://github.com/pmd/pmd/issues/760 we found that the parser is accepting invalid Apex code.

Instead of writing 

```
if (someVariable.equals(someValue)) {
   System.debug(someValue);
}
```

the user had this with a missing ")"

```
if (someVariable.equals(someValue) {
   System.debug(someValue);
}
```

We couldn't reproduce this error in the Force.com IDE or the Developer Console which seems to reject this as an error.

But when you load the problematic code into the AST viewer of PMD you notice the if is parsed, even without the closing ), and the method moreMethod is parsed too. It never stoped. The exception log is empty.

![33287264-ebd6788a-d396-11e7-90f2-92469882ec76](https://user-images.githubusercontent.com/8180281/33288635-488f12dc-d3bd-11e7-9192-75d46a196874.png)

**Comment by up2go-rsoesemann** [comment]
FYI: @wadewegner @vazexqi @jamesward

**Comment by adangel** [comment]
FYI - the version we use is from here: https://github.com/forcedotcom/idecore/tree/master/com.salesforce.ide.apex.core/lib and it looks like 2 years old...

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
