### ISSUE TITLE
Will Jorje Parser be updated or replaced by Language Server?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [forcedotcom/idecore#237]
This issue shadow the related discussion in the PMD repo https://github.com/pmd/pmd/issues/677#issuecomment-337746976

It's about the question on which future versions of PMD should built on? In the comments there are rumors that Jorje will not be updated for language extensions like "Switch". 

We PMD maintainer would need some help by Salesforce to better understand the roadmap.

**Comment by vazexqi** [comment]
I will reply to https://github.com/pmd/pmd/issues/677#issuecomment-337746976 and close this issue.

**Comment by up2go-rsoesemann** [comment]
Thanks @vazexqi for your quick response.
