### ISSUE TITLE
Saving a file locally marks it as dirty

### ISSUE THREAD

**Issue by nathanhinchey** [forcedotcom/idecore#239]
### Summary
Saving a file locally marks it as dirty, triggering a warning alert when attempting to save to the server.

### Steps To Reproduce:
1. In Eclipse, save a file locally with no errors or warnings
1. in the package manager, right click on the file and save it to the server

### Expected result
No warning appears about dirtiness of the resource

### Actual result
Warning alert that the resource is dirty appears

### Additional information

_Feel free to attach a screenshot_.

**Force.com IDE version**: 42

**OS and version**: macOS High Sierra Version 10.13.2

**Java version**: 1.8.0_152

**Eclipse version**: Oxygen.2 Release (4.7.2)

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).
