### ISSUE TITLE
Please open source Force.com IDE 2

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#242]
I doubt I will be the only that twill find a switch away from Eclipse to be a difficult task, especially if many years have been invested and if just works fine. I am currently investing the effort into vscode but for my needs I find it still a rudimentary IDE at best.

So having said that I ask that the Force.com IDE 2 beta be also released as open source, @vazexqi you would you be able to take this request up the chain to see if it's feasible? 

Be great,

**Comment by ntotten** [comment]
This is something we have thought about, but there are several issues with this. The most significant though is that right now to build the IDE requires use of a number of internal only tools and dependencies that we will not be able to open source. This means that to open source the Force.com IDE 2 would require a reasonable amount of engineering effort. Second, there would be efforts around project ownership and support - this is not something we are able to do.

Given that this effort would take away resources from projects such as the CLI and VS Code we don't feel that the benefit is enough to the community. That being said, we know that VS Code won't be the right tool for everybody. With the release of the CLI, our language servers, and more we are trying to make it as easy as possible for third-parties to build tooling for Salesforce on other platforms (Illuminated Cloud, Welkins Suite, etc.). 

We know that the transition to new tooling can be difficult and we recognize that VS Code doesn't yet have all the features needed to move from Eclipse. We are going to be continuing to add new features to VS Code and we will not deprecate the Force.com IDE v1 until VS Code handles the development flows that you use today in Eclipse.
