### ISSUE TITLE
Lightning Component part of a Managed Package does not hide any part of the code in Eclipse IDE

### ISSUE THREAD

**Issue by vc4u** [forcedotcom/idecore#245]
### Summary
If we package a Lightning Component in a Managed Package, the IDE downloads all Referenced Package in the subscribe org as part of the project. In that, it downloads all the Lightning Components of teh package, and I can simply Open the Component, with it's Markup, Controller, Helper and all files as if I'm editing the component in the project. While Developer Console in the same org will show (hidden) message on opening the same component.

### Steps To Reproduce:
1. Create Lightning Component
2. Create a new Managed Package
3. Upload the Lightning Component as part of managed package.
4. Install into a Test Org.
5. Create a Force.com IDE project for the Test Org.
6. Refresh content into the project.
7. Browse Referenced Packages folder in the Eclipse Project Viewer
8. Step into the respective App/namespace the package was uploaded as.
9. Double click to open the Component in Eclipse Editor.
10. You can see the Full Source Code of the Project this way.

### Expected result
Managed Package code should be Hidden always.

### Actual result
Managed Package code is shown to end user and it can be copied without any issues.

**Force.com IDE version**:
Force.com IDE	38.0.0.201701101558

**OS and version**:
Windows 10 x64

**Java version**:
1.7

**Comment by vazexqi** [comment]
The Force.com IDE uses the Metadata API to do its retrieval of components. I have created a sample managed package and installed it in my org. When I use the Metadata API to retrieve that package, I am able to see all the sources.

Note that this behavior is not limited to the Force.com IDE. Any IDE or tool that uses the Metadata API such as the Salesforce CLI, the ant migration tool, etc can see the source of the managed package.

When I use the Developer Console, it is using the Tooling API, i.e, services/data/v43.0/tooling/sobjects/AuraDefinition/0Adxx000000000VCAQ

The behavior of the two APIs appears to be different. I've opened an internal investigation and we will confirm whether this is working-as-designed or a bug with the proper team.

**Comment by ntotten** [comment]
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. See: https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html
