### ISSUE TITLE
PMD parsing exception for Apex classes using 'inherited sharing' keyword

### ISSUE THREAD

**Issue by avesolovksyy** [forcedotcom/idecore#247]
### Summary
We are running pmd against our apex classes written in 44.0 SF api version.
Bunch of the classes are using 'inherited sharing' keywords.
And all such classes fail with an error message when parsing by PMD:

> net.sourceforge.pmd.lang.ast.ParseException: Couldn't parse the source - there is not root node - Syntax Error??

After getting rid off 'inherited sharing', classes have been parsed successfully.

### Steps To Reproduce:
1. Declare a simple class using 'inherited sharing' keyword
1. Run it through PMD (we are using ant to trigger static code analysis, pmd version 6.10)

### Expected result
Expected to see some vulnerabilities/bad practices detected by pmd. 

### Actual result
All classes with 'inherited sharing' keyword have failed with an error: 
> net.sourceforge.pmd.lang.ast.ParseException: Couldn't parse the source - there is not root node - Syntax Error??

Other classes without this keyword have succeeded.
Also removal of this keyword from failed classes results in success as well.

### Question
Does the latest pmd version supports latest SF API, i.e. 44?

**Comment by ntotten** [comment]
At this point, I think that you will need to move over to consume the bundled jar that ships with VS Code: https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex/out

Given that we are deprecating the Force.com IDE it no longer makes sense to keep updating this repo. The version that ships with VS Code is updated when any change is made to jorje.
