### ISSUE TITLE
Feature: Test Runner highlight coverage in editor view

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#28]
Perhaps we could highlight lines not covered by the test in the editor for better ui experience? The line ruler would make good sense for it:

![image](https://cloud.githubusercontent.com/assets/273413/3627193/7708185c-0e86-11e4-86c9-1358a663d1ca.png)

**Comment by DatGuyJonathan** [comment]
This was added in v36: https://developer.salesforce.com/docs/atlas.en-us.200.0.eclipse.meta/eclipse/runTests.htm
