### ISSUE TITLE
Request: Auto document, formatting and colors for code

### ISSUE THREAD

**Issue by Nivg** [forcedotcom/idecore#38]
Hi,
First thanks all for the great job, and thanks for sharing the source code.

Requests:
1. Code Colors: One of the things that bother me as a developer which use to setting his environment with colors that enhance my code view, and are more healthy to my eyes his colors, when trying to use java themes plugin for Eclipse, the code colors are bad, some even invisible.
2. The ability of typing auto doc comments for the Force.com IDE. For example, when using Netbeans for creating Javadoc Stubs:
Place the cursor above a method or a class that has no Javadoc, type "/**", and press Enter. The IDE creates a skeletal structure for a Javadoc comment filled with some content.
3. Auto formatter of code, like Netbeans CTRL-SHIFT-F for java.

I am currently using mavens mate as it provides 2/3:
1. Built-in Colors.
2. Auto doc, when using DocBlockr plugin (after editing the code to think Apex is Java, works great except for map parameters).
![mmcolorsdoc](https://cloud.githubusercontent.com/assets/6303616/3711075/f59ea2ca-14bd-11e4-800d-ebb922b2ea48.PNG)

Thanks.

**Comment by RJPalombo** [comment]
Hi @Nivg have you had time to look into this by any chance?  

@vazexqi is there any way this can get some attention? Of if possible, point me in the right direction  so I can share with my dev team.
