### ISSUE TITLE
[FEATURE] Enable Task Tags Support

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#50]
Currently 'Task Tags' does not appear to be working for `.cls` files but does work for `.page` files; please enable Task Tags support for any files under the `/src` folder.

As a work around I attempted to add `*.cls` as an HTML content type but with no success. 

![image](https://cloud.githubusercontent.com/assets/273413/3982487/3ee266b6-2877-11e4-83d0-daf93ff34bb8.png)

**Comment by ImJohnMDaniel** [comment]
@vazexqi - QQ - Is this on your radar for Force.com IDE v2.0??

It really would be a great feature to have!!!!
