### ISSUE TITLE
Field Permissions Removed from Object

### ISSUE THREAD

**Issue by Sonal4J** [forcedotcom/idecore#56]
I upgraded the code to version 31 using IDE. Now when I deploy the code custom fields do not have the permissions and I have to manually add permissions to the Object fields. In the previous versions custom Objects used to have permissions for all fields after deployment

**Comment by vazexqi** [comment]
@Sonal4J Sorry for the slow reply. This is the new behavior for the Metadata API v31 and working as designed. The product manager says: "you must migrate the profile to get the FLS carried over".
