### ISSUE TITLE
Variables in managed packaged can't be used

### ISSUE THREAD

**Issue by mhooghiemstra79** [forcedotcom/idecore#68]
In a current project I am using the Zuora 360 managed packaged.
I currently updated to the new force.com ide (Version: Summer '14 (31.0.0))
I now have the issue that code that previously saved without any issues can't be saved anymore. The error Eclipse provides is the following.
Compilation error: Package Visibility: Variable is not visible.

A colleague, working with an older ide version, doesn't have this issue saving the same code.

**Comment by chowwinston** [comment]
No response from user. Even if this issue existed it should be fine now.
