### ISSUE TITLE
Parsing Error in Apex Class editor for fields with digits in the name

### ISSUE THREAD

**Issue by sfdev99** [forcedotcom/idecore#72]
If a field on a custom object has a digit in the name (e.g, A2D_Place__c) the Apex editor throws an error when the class is opened in the editor. 

If the code is edited and saved, forcing a server side save and workspace build, the error goes away - until the file is closed and re-opened in the editor. 

++++++
Description	Resource	Path	Location	Type
Syntax(error = UnexpectedSyntaxError(loc = RealLoc(startIndex = 537, endIndex = 550, line = 96, column = 13), message = missing SEMICOLON at 'D_Place__c'))	MyCode.cls	/MyProject/src/classes	/MyProject/src/classes/MyCode.cls	Force.com compilation problem

**Comment by RJPalombo** [comment]
Sounds like this can be closed?
