### ISSUE TITLE
Force.com deploy ask for password, even when password is already set in Project Configuration

### ISSUE THREAD

**Issue by orlando** [forcedotcom/idecore#78]
The idea is to use the stored passwords instead of entering the password every time you want to deploy code to Salesforce

**Comment by smohyee** [comment]
Also agreed that this would be a nice improvement. 

Similar to MavensMate, I propose that Force.com allow you to create and maintain multiple connections with other SF instances. Then, when deploying, you simply select the destination, and the stored login/password/token are used.
