### ISSUE TITLE
[FEATURE] Add `*-meta.xml` navigation filter

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#81]
It would be helpful to add a `*-meta.xml` filter for the 'Navigation' view; some helpful info here: http://stackoverflow.com/questions/2396297/adding-a-filter-to-the-project-explorer-in-eclipse

![salesforce-ide-feature-request-navigation-filter2](https://cloud.githubusercontent.com/assets/273413/5030228/49f86b76-6b1c-11e4-9317-ab81da79b88b.png)
![salesforce-ide-feature-request-navigation-filter](https://cloud.githubusercontent.com/assets/273413/5030227/49f867b6-6b1c-11e4-89f1-822c21bde809.png)

**Comment by Jak0bd** [comment]
Hi Daniel,

You could also solve this by using the Package Explorer view. This view does allow you to filter on the meta.xml files:
![image](https://cloud.githubusercontent.com/assets/8047787/6799553/14215a3c-d217-11e4-9225-d21282040a40.png)

**Comment by andrew-chiz-muzychuk** [comment]
Strange... I've filtered xmls out from Navigator view with 
right click on src folder -> Properties ; then Resource -> Resource Filters ; then Add... Name matches *.xml (recursive).
All xmls are gone.
Thanks for the issue here. They always pissed me off = ))

**Comment by ram4ufriends** [comment]
Yeah, there is know real good way of filtering out meta xmls I guess. When you open resource window (Cntrl+Shift+R) it shows meta xmls.

**Comment by chowwinston** [comment]
Given the workarounds described in this thread as well as the new [open apex type](https://github.com/forcedotcom/idecore/wiki/Changes-in-Force.com-IDE-Beta-Version-37.0.0.20160512#easily-open-apex-classes-and-triggers-with-open-type) feature coming in v37, this will not be prioritized.
