### ISSUE TITLE
Wiki page needed explaining what the beta version consists of and what the release cycle and schedule looks like

### ISSUE THREAD

**Issue by KeithClarke** [forcedotcom/idecore#86]
Issue #85 asks for the API 32 (Winter 15) release date. In issue #20 you ask for help on a feature but with no explanation of the time window available.

Personally, I'd like to understand what the beta version is (a nightly build or some kind of release candidate?) and also have some sense of what the overall release process you use is and a sketch of when you plan to do releases. I (and maybe others) might then be more encouraged to try out the beta version perhaps resulting in a few less bugs in the final release.

**Comment by JohnDTheMaven** [comment]
@vazexqi and @kaplanjosh 

Are there any plans for a new release for v33?  As it stands right now, to use the Force.com IDE, we are stuck on v31 API.  I understand your desire to not release along SFDC release boundaries but at the same time we need a release now that will allow us as developers to keep up with the new APIs. 

Even releasing an updated version of the Beta plugin would be helpful.

**Comment by vazexqi** [comment]
@JohnDTheMaven Could you elaborate more on which newer APIs you are interested in?

The 194.eclipse branch contains the v33 of the API (it's in GitHub so you can take a look as well). However, we are only using the new things that are exposed in the Tooling API – for debugger work. We are not consuming any of the new metadata in the Metadata API.

**Comment by JohnDTheMaven** [comment]
@vazexqi - When I create new Apex classes or other metadata objects, they are defaulting to v31 and will not allow me to create these objects as v32 or higher API.  In this case, I am not interested in the newer APIs.  I just simply want the ability to create Apex/VF files with the latest API version.

**Comment by vazexqi** [comment]
Ah, OK. Thanks for the clarifications!

**Comment by JohnDTheMaven** [comment]
@vazexqi and @kaplanjosh 

Please forgive me for being persistent with this question, but are there any plans for a new release for v33?

I appreciate the help and information.

Cheers!

**Comment by kaplanjosh** [comment]
In general, we won't be releasing any more v xx updates of the plug-in.  When we do a release, we will quite probably update the metadata API version, but we do not plan to do the steps needed to hook the "add metadata to project" wizard and such.  

We do plan to release a new version of the plug-in in the coming weeks, assuming all goes well. This will likely have the v33 metadata API incorporated, which would likely update the default version of artifacts to v33. 

The process of adding a new version of the Metadata API and Tooling API should be one you can take on in a branch of the project.  The WSDL for your org may not have everything that's in the "add metadata" wizard, but it would certainly have the Apex & Visualforce items in it.  You might even find ways to improve on the existing process - please create issues for any such places you see for improvement.
