### ISSUE TITLE
Reappearance(?) of Compiler Error "mismatched input 'Case' expecting ... "

### ISSUE THREAD

**Issue by Duncan-Stewart** [forcedotcom/idecore#92]
Closed issue https://github.com/forcedotcom/idecore/issues/34 looks like what I've been experiencing the last couple of days after installing the latest Force.com IDE.  A couple of times I was able to resolve it by refreshing the affected class(es) from the server, but not today :(
My Class starts out like this - error occurs in the initial class definition - 

public class NxTSEscalationScore {

  public NxTSEscalationScore(Case[] cases, Map<Id, Case> newMap, Map<Id, Case> oldMap) {
   
Syntax(error = UnexpectedSyntaxError(loc = RealLoc(startIndex = 14, endIndex = 18, line = 10, column = 30), message = mismatched input 'Case' expecting RPAREN))

Eclipse: Kepler Build id: 20130614-0229
Force.com IDE: 31

Is there a quick fix for this?  I had to change my JRE to support an (AppExchange) application, at which point my previous Force.com IDE (30) stopped working correctly so I upgraded.  Should I revert to IDE 30?

**Comment by vazexqi** [comment]
@Duncan-Stewart This error can be ignored. It's only a local error that should not prevent you from syncing to your org. 

I can summarize the issue quickly - we are planning to introduce a switch statement feature at some point and have begun doing that in the new parser. However, as you can see there might be some confusion with the Case (a salesforce object) under different parse conditions.

I'll take a look but you should be able to continue saving to the server without any effects. You can verify this by opening the saved file in the Developer Console or the Setup pages in your org. Hope this helps!

**Comment by Duncan-Stewart** [comment]
Ah - okay, thanks!  

Now I have (no excuse not) to get back to coding, I suppose ...

**Comment by vazexqi** [comment]
Closing this because Map myMap is syntactically incorrect in Apex and what the IDE is reporting is consistent.
