### ISSUE TITLE
Enhanced Template Support

### ISSUE THREAD

**Issue by fdutton** [forcedotcom/idecore#97]
##### User Story
As a Salesforce Developer, I wish to modify existing Apex and Visualforce templates, add new templates and share templates so that I can standardize my organization's use of the Force.com IDE.

##### Acceptance Criteria
1. All templates should be available through the standard Eclipse preferences mechanism
2. When creating a new file, I should be presented with a list of applicable templates. For example, if I am  creating a new Apex class then the IDE will only present templates that are relevant to creating an Apex class.
3. I should be able to export one or more templates for use by my coworkers.
4. I should be able to import templates into my workspace created by another.
5. I should be able to remove any templates that I do not wish to be available in my workspace.
6. I should be able to revert any template from its modified form back to its original definition.
7. The system should provide a way to edit templates.
8. The system should present the templates during editing the same way as the associated editor (e.g., When editing Apex code, the template editor will show the same colors and fonts as the Apex Editor).

**Comment by vazexqi** [comment]
@fdutton 

1. Are you talking about file templates or code snippets? Or both?
1. What do you mean by "standard Eclipse preferences mechanism"? Are you referring from what you get from going to Preferences > Java > Code Style > Code Templates?

I don't use templates much (maybe the occasional code snippet for the for loop)  so I just want to make sure I understand the use cases here.

**Comment by kaplanjosh** [comment]
To be clear, you are talking about creating templates that you would like to use in your organization, rather than templates that you think should be globally available (like the template that creates different types of Apex classes in the New->Apex Class flow).  Correct?

**Comment by fdutton** [comment]
@vazexqi 
1. The user can create either file templates or code snippets. I have written the code to support file templates but have not determined what is needed to support code snippets yet.
2. This just means that template management exists as a preference page. This is where a user would expect to find it since all the other editors place template management there (e.g., JDT, HTML, XML, etc).

@kaplanjosh
Eclipse supports both. I plan to move the half dozen templates from TemplateRepository to an Eclipse TemplateStore. These would be the default templates that ship with the IDE. The user is free to add new templates, edit and remove existing templates (including those that ship).

**Comment by fdutton** [comment]
@vazexqi 
The one thing I am unable to do is add content to the documentation. Is it possible to add the existing documentation plug-in to the source repository?

**Comment by fdutton** [comment]
Changes applied in #98.
